package ch.bfh.ti.soed.white.mhc_pms.ui;

import ch.bfh.ti.soed.white.mhc_pms.security.UIPermission;
import ch.bfh.ti.soed.white.mhc_pms.security.UserSingleton;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;

class CaseInfoComponent extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnNewCase;
	@AutoGenerated
	private Button btnEditCaseData;
	private static final long serialVersionUID = -1488922640521851182L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CaseInfoComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		
		UIPermission permission = UserSingleton.getUser().getUIPermission();
		this.btnNewCase.setEnabled(permission.isNewCaseAllowed());
		this.btnEditCaseData.setEnabled(permission.isEditCaseDataAllowed());
	}

	protected void updateComponentDataSource() {
		// TODO Auto-generated method stub
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// btnEditCaseData
		btnEditCaseData = new Button();
		btnEditCaseData.setCaption("Fallinfo bearbeiten");
		btnEditCaseData.setImmediate(true);
		btnEditCaseData.setWidth("-1px");
		btnEditCaseData.setHeight("-1px");
		mainLayout.addComponent(btnEditCaseData, "top:20.0px;left:20.0px;");
		
		// btnNewCase
		btnNewCase = new Button();
		btnNewCase.setCaption("Neuer Fall");
		btnNewCase.setImmediate(true);
		btnNewCase.setWidth("-1px");
		btnNewCase.setHeight("-1px");
		mainLayout.addComponent(btnNewCase, "top:20.0px;left:200.0px;");
		
		return mainLayout;
	}

}
