package ch.bfh.ti.soed.white.mhc_pms.ui;

import ch.bfh.ti.soed.white.mhc_pms.controller.NavigationEvent;
import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentController;
import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentListener;
import ch.bfh.ti.soed.white.mhc_pms.data.PCase;
import ch.bfh.ti.soed.white.mhc_pms.data.PmsDataAccess;
import ch.bfh.ti.soed.white.mhc_pms.data.PmsDataAccessCreator;
import ch.bfh.ti.soed.white.mhc_pms.security.PmsPermission;
import ch.bfh.ti.soed.white.mhc_pms.security.PmsPermission.Element;
import ch.bfh.ti.soed.white.mhc_pms.util.ValueConverter;

import com.vaadin.addon.jpacontainer.EntityItem;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Reindeer;

/**
 * @author		Gruppe White, I2p, BFH Bern, <a href="https://github.com/fabaff/ch.bfh.bti7081.s2013.white">Contact</a>
 * @version		0.0.2 
 * @since		0.0.1
 * 
 * UI Class for case information
 */
class CaseInfoComponent extends PmsComponentController implements PmsComponentListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label lblView;
	@AutoGenerated
	private Panel panMaster;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Panel panCase;
	@AutoGenerated
	private FormLayout formLayout_3;
	@AutoGenerated
	private Label lblDateCaseClosed;
	@AutoGenerated
	private Label lblDateCaseOpended;
	@AutoGenerated
	private Panel pan2;
	@AutoGenerated
	private FormLayout formLayout_2;
	@AutoGenerated
	private Label lblJudicialStatus;
	@AutoGenerated
	private Label lblVacation;
	@AutoGenerated
	private Label lblDegreeOfDanger;
	@AutoGenerated
	private Label lblSanction;
	@AutoGenerated
	private Label lblAssignment;
	@AutoGenerated
	private Panel pan1;
	@AutoGenerated
	private FormLayout formLayout_1;
	@AutoGenerated
	private Label lblOrderOfPatient;
	@AutoGenerated
	private Label lblGoOutStatus;
	@AutoGenerated
	private Label lblSuicidalTendency;
	@AutoGenerated
	private Label lblKindOfTreatment;
	@AutoGenerated
	private Label lblReanimationStatus;
	@AutoGenerated
	private Button btnNewCase;
	@AutoGenerated
	private Button btnEditCaseData;
	private static final long serialVersionUID = -1488922640521851182L;

	private PmsDataAccess pmsContainers;
	
	private PmsPermission permission;
	
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public CaseInfoComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		this.pmsContainers = PmsDataAccessCreator.getDataAccess();
		this.pmsContainers.getPCaseContainer().refresh();
		Object itemId = this.pmsContainers.getPCaseContainer().getCurrentPCaseId();
		this.permission = new PmsPermission(this.pmsContainers.getCurrentUser().getUserGroup());

		this.addNewCaseListener();
		this.addEditCaseListener();
		this.pCaseItemChange(itemId);
		
		// Static elements
		this.lblView.addStyleName(Reindeer.LABEL_H2);
		this.lblView.setValue("Fälle");
	}

	private void addEditCaseListener() {
		this.btnEditCaseData.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = 8636612818445844248L;
			
			@Override
			public void buttonClick(ClickEvent event) {
				CaseInfoComponent.this.fireUIActivationEvent(false);
				CaseInfoComponent.this.fireComponentChangeEvent(NavigationEvent.PCASE);
			}
		});
	}

	private void addNewCaseListener() {
		this.btnNewCase.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = 8636612818445844248L;
			
			@Override
			public void buttonClick(ClickEvent event) {
				CaseInfoComponent.this.fireUIActivationEvent(false);
				CaseInfoComponent.this.fireComponentChangeEvent(NavigationEvent.PCASE);
				CaseInfoComponent.this.fireNewCaseEvent(true);
			}
		});
	}

	@Override
	public void pCaseItemChange(Object itemId) {
		EntityItem<PCase> entityItem = this.pmsContainers.getPCaseContainer().getItem(itemId);
		PCase item = new PCase();
		
		if (entityItem != null) {
			item = entityItem.getEntity();
		} 
		
		this.lblAssignment.setValue(item.getAssignment());
		this.lblDateCaseClosed.setValue(ValueConverter.convertDate(item.getDateCaseClosed()));
		this.lblDateCaseOpended.setValue(ValueConverter.convertDate(item.getDateCaseOpened()));
		this.lblDegreeOfDanger.setValue(item.getDegreeOfDanger());
		this.lblGoOutStatus.setValue(item.getGoOutStatus());
		this.lblJudicialStatus.setValue(item.getJudicialStatus());
		this.lblOrderOfPatient.setValue(ValueConverter.convertString(item.getOrderOfPatient()));
		this.lblReanimationStatus.setValue(ValueConverter.convertString(item.getReanimationStatus()));
		this.lblSanction.setValue(item.getSanction());
		this.lblSuicidalTendency.setValue(item.getSuicidalTendency());
		this.lblVacation.setValue(item.getVacation());
		this.lblKindOfTreatment.setValue(ValueConverter.convertString(item.getKindOfTreatment()));
		
		this.btnNewCase.setEnabled(permission.hasPermission(Element.NEW_CASE) && itemId != null);
		this.btnEditCaseData.setEnabled(permission.hasPermission(Element.EDIT_CASE) && itemId != null);
	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// btnEditCaseData
		btnEditCaseData = new Button();
		btnEditCaseData.setCaption("Fallinfo bearbeiten");
		btnEditCaseData.setImmediate(true);
		btnEditCaseData.setWidth("140px");
		btnEditCaseData.setHeight("-1px");
		mainLayout.addComponent(btnEditCaseData, "top:20.0px;left:250.0px;");
		
		// btnNewCase
		btnNewCase = new Button();
		btnNewCase.setCaption("Neuer Fall");
		btnNewCase.setImmediate(true);
		btnNewCase.setWidth("-1px");
		btnNewCase.setHeight("-1px");
		mainLayout.addComponent(btnNewCase, "top:20.0px;left:400.0px;");
		
		// panMaster
		panMaster = buildPanMaster();
		mainLayout.addComponent(panMaster, "top:60.0px;left:20.0px;");
		
		// lblView
		lblView = new Label();
		lblView.setImmediate(false);
		lblView.setWidth("-1px");
		lblView.setHeight("-1px");
		lblView.setValue("Label");
		mainLayout.addComponent(lblView, "top:20.0px;left:20.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanMaster() {
		// common part: create layout
		panMaster = new Panel();
		panMaster.setImmediate(false);
		panMaster.setWidth("-1px");
		panMaster.setHeight("-1px");
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		panMaster.setContent(verticalLayout_4);
		
		return panMaster;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("100.0%");
		verticalLayout_4.setHeight("100.0%");
		verticalLayout_4.setMargin(false);
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		verticalLayout_4.addComponent(gridLayout_1);
		
		return verticalLayout_4;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("-1px");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(true);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setColumns(2);
		gridLayout_1.setRows(2);
		
		// pan1
		pan1 = buildPan1();
		gridLayout_1.addComponent(pan1, 0, 0);
		
		// pan2
		pan2 = buildPan2();
		gridLayout_1.addComponent(pan2, 1, 0);
		
		// panCase
		panCase = buildPanCase();
		gridLayout_1.addComponent(panCase, 0, 1);
		
		return gridLayout_1;
	}

	@AutoGenerated
	private Panel buildPan1() {
		// common part: create layout
		pan1 = new Panel();
		pan1.setCaption("           ");
		pan1.setImmediate(false);
		pan1.setWidth("-1px");
		pan1.setHeight("-1px");
		
		// formLayout_1
		formLayout_1 = buildFormLayout_1();
		pan1.setContent(formLayout_1);
		
		return pan1;
	}

	@AutoGenerated
	private FormLayout buildFormLayout_1() {
		// common part: create layout
		formLayout_1 = new FormLayout();
		formLayout_1.setImmediate(false);
		formLayout_1.setWidth("320px");
		formLayout_1.setHeight("100.0%");
		formLayout_1.setMargin(true);
		formLayout_1.setSpacing(true);
		
		// lblReanimationStatus
		lblReanimationStatus = new Label();
		lblReanimationStatus.setCaption("Reanimationsstatus: ");
		lblReanimationStatus.setImmediate(false);
		lblReanimationStatus.setWidth("-1px");
		lblReanimationStatus.setHeight("18px");
		lblReanimationStatus.setValue("Label");
		formLayout_1.addComponent(lblReanimationStatus);
		
		// lblKindOfTreatment
		lblKindOfTreatment = new Label();
		lblKindOfTreatment.setCaption("Behandlungsart:");
		lblKindOfTreatment.setImmediate(false);
		lblKindOfTreatment.setWidth("-1px");
		lblKindOfTreatment.setHeight("-1px");
		lblKindOfTreatment.setValue("Label");
		formLayout_1.addComponent(lblKindOfTreatment);
		
		// lblSuicidalTendency
		lblSuicidalTendency = new Label();
		lblSuicidalTendency.setCaption("Suizidalität: ");
		lblSuicidalTendency.setImmediate(false);
		lblSuicidalTendency.setWidth("-1px");
		lblSuicidalTendency.setHeight("18px");
		lblSuicidalTendency.setValue("Label");
		formLayout_1.addComponent(lblSuicidalTendency);
		
		// lblGoOutStatus
		lblGoOutStatus = new Label();
		lblGoOutStatus.setCaption("Ausgang: ");
		lblGoOutStatus.setImmediate(false);
		lblGoOutStatus.setWidth("-1px");
		lblGoOutStatus.setHeight("18px");
		lblGoOutStatus.setValue("Label");
		formLayout_1.addComponent(lblGoOutStatus);
		
		// lblOrderOfPatient
		lblOrderOfPatient = new Label();
		lblOrderOfPatient.setCaption("Patientenverfügung:");
		lblOrderOfPatient.setImmediate(false);
		lblOrderOfPatient.setWidth("-1px");
		lblOrderOfPatient.setHeight("18px");
		lblOrderOfPatient.setValue("Label");
		formLayout_1.addComponent(lblOrderOfPatient);
		
		return formLayout_1;
	}

	@AutoGenerated
	private Panel buildPan2() {
		// common part: create layout
		pan2 = new Panel();
		pan2.setCaption("           ");
		pan2.setImmediate(false);
		pan2.setWidth("-1px");
		pan2.setHeight("-1px");
		
		// formLayout_2
		formLayout_2 = buildFormLayout_2();
		pan2.setContent(formLayout_2);
		
		return pan2;
	}

	@AutoGenerated
	private FormLayout buildFormLayout_2() {
		// common part: create layout
		formLayout_2 = new FormLayout();
		formLayout_2.setImmediate(false);
		formLayout_2.setWidth("320px");
		formLayout_2.setHeight("100.0%");
		formLayout_2.setMargin(true);
		formLayout_2.setSpacing(true);
		
		// lblAssignment
		lblAssignment = new Label();
		lblAssignment.setCaption("Zuweiser: ");
		lblAssignment.setImmediate(false);
		lblAssignment.setWidth("-1px");
		lblAssignment.setHeight("18px");
		lblAssignment.setValue("Label");
		formLayout_2.addComponent(lblAssignment);
		
		// lblSanction
		lblSanction = new Label();
		lblSanction.setCaption("Zwangsmassnahmen: ");
		lblSanction.setImmediate(false);
		lblSanction.setWidth("-1px");
		lblSanction.setHeight("18px");
		lblSanction.setValue("Label");
		formLayout_2.addComponent(lblSanction);
		
		// lblDegreeOfDanger
		lblDegreeOfDanger = new Label();
		lblDegreeOfDanger.setCaption("Fremdgefährtung: ");
		lblDegreeOfDanger.setImmediate(false);
		lblDegreeOfDanger.setWidth("-1px");
		lblDegreeOfDanger.setHeight("18px");
		lblDegreeOfDanger.setValue("Label");
		formLayout_2.addComponent(lblDegreeOfDanger);
		
		// lblVacation
		lblVacation = new Label();
		lblVacation.setCaption("Urlaub: ");
		lblVacation.setImmediate(false);
		lblVacation.setWidth("-1px");
		lblVacation.setHeight("18px");
		lblVacation.setValue("Label");
		formLayout_2.addComponent(lblVacation);
		
		// lblJudicialStatus
		lblJudicialStatus = new Label();
		lblJudicialStatus.setCaption("Juristischer Status: ");
		lblJudicialStatus.setImmediate(false);
		lblJudicialStatus.setWidth("-1px");
		lblJudicialStatus.setHeight("18px");
		lblJudicialStatus.setValue("Label");
		formLayout_2.addComponent(lblJudicialStatus);
		
		return formLayout_2;
	}

	@AutoGenerated
	private Panel buildPanCase() {
		// common part: create layout
		panCase = new Panel();
		panCase.setCaption("Fall-Daten");
		panCase.setImmediate(false);
		panCase.setWidth("-1px");
		panCase.setHeight("-1px");
		
		// formLayout_3
		formLayout_3 = buildFormLayout_3();
		panCase.setContent(formLayout_3);
		
		return panCase;
	}

	@AutoGenerated
	private FormLayout buildFormLayout_3() {
		// common part: create layout
		formLayout_3 = new FormLayout();
		formLayout_3.setImmediate(false);
		formLayout_3.setWidth("320px");
		formLayout_3.setHeight("100.0%");
		formLayout_3.setMargin(true);
		formLayout_3.setSpacing(true);
		
		// lblDateCaseOpended
		lblDateCaseOpended = new Label();
		lblDateCaseOpended.setCaption("Datum Falleröffung: ");
		lblDateCaseOpended.setImmediate(false);
		lblDateCaseOpended.setWidth("-1px");
		lblDateCaseOpended.setHeight("18px");
		lblDateCaseOpended.setValue("Label");
		formLayout_3.addComponent(lblDateCaseOpended);
		
		// lblDateCaseClosed
		lblDateCaseClosed = new Label();
		lblDateCaseClosed.setCaption("Datum Fallabschluss: ");
		lblDateCaseClosed.setImmediate(false);
		lblDateCaseClosed.setWidth("-1px");
		lblDateCaseClosed.setHeight("18px");
		lblDateCaseClosed.setValue("Label");
		formLayout_3.addComponent(lblDateCaseClosed);
		
		return formLayout_3;
	}

}
