package ch.bfh.ti.soed.white.mhc_pms.ui;

import ch.bfh.ti.soed.white.mhc_pms.controller.NavigationEvent;
import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentController;
import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentListener;
import ch.bfh.ti.soed.white.mhc_pms.data.PmsDataAccess;
import ch.bfh.ti.soed.white.mhc_pms.data.PmsDataAccessCreator;
import ch.bfh.ti.soed.white.mhc_pms.data.UnknownUserException;
import ch.bfh.ti.soed.white.mhc_pms.security.PmsPermission;
import ch.bfh.ti.soed.white.mhc_pms.security.PmsPermission.Operation;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Reindeer;

/**
 * 
 * @author Group White, I2p, BFH Berne, <a
 *         href="https://github.com/fabaff/ch.bfh.bti7081.s2013.white"
 *         >Contact</a>
 * @version 1.0.0
 * 
 */
public class DiagnosisDetailComponent extends PmsComponentController implements
		PmsComponentListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Panel panel_3;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Button btnNewDiagnosis;
	@AutoGenerated
	private Button btnToggleDiagnosisView;
	@AutoGenerated
	private Label lblTitle;
	private static final long serialVersionUID = 4997014971018144148L;

	private PmsDataAccess pmsDataAccess;

	private PmsPermission permission;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public DiagnosisDetailComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		try {
			this.pmsDataAccess = PmsDataAccessCreator.getDataAccess();
			this.permission = new PmsPermission(this.pmsDataAccess
					.getCurrentUser().getUserGroup());

			this.addToggleDiagnosisViewButtonListener();
			this.addNewDiagnosisButtonListener();
			this.pCaseItemChange();

			// Static elements
			this.lblTitle.addStyleName(Reindeer.LABEL_H2);
		} catch (UnknownUserException e) {
			Notification.show(e.getInvalidUserMessage(),
					Notification.Type.HUMANIZED_MESSAGE);
		}

		// TODO closed cases: lock diag edit
	}

	private void addNewDiagnosisButtonListener() {
		this.btnNewDiagnosis.addClickListener(new Button.ClickListener() {

			private static final long serialVersionUID = -7261845370145460948L;

			@Override
			public void buttonClick(ClickEvent event) {
				DiagnosisDetailComponent.this.fireUIActivationEvent(false);
				DiagnosisDetailComponent.this
						.fireComponentChangeEvent(NavigationEvent.EDIT_DIAGNOSIS);
				DiagnosisDetailComponent.this.fireNewCaseEvent(true);
			}
		});
	}

	private void addToggleDiagnosisViewButtonListener() {
		this.btnToggleDiagnosisView
				.addClickListener(new Button.ClickListener() {

					private static final long serialVersionUID = 7009987843107108151L;

					@Override
					public void buttonClick(ClickEvent event) {
						DiagnosisDetailComponent.this
								.fireComponentChangeEvent(NavigationEvent.DIAGNOSIS_TABLE);
					}
				});
	}

	@Override
	public void enter(ViewChangeEvent event) {
		this.pmsDataAccess.getDiagnosisContainer().refresh();
		
		this.setPermissions();
		// TODO Auto-generated method stub
		
	}
	
	private void setPermissions() {
		
		
		this.btnNewDiagnosis.setEnabled(permission
				.hasPermission(Operation.NEW_DIAGNOSIS));

		// TODO set Permissions in detail panel
		// this.btnEditDiagnosis.setEnabled(permission
		// .hasPermission(Operation.EDIT_DIAGNOSIS));
		// this.btnDeleteDiagnosis.setEnabled(permission
		// .hasPermission(Operation.DELETE_DIAGNOSIS));
	}

	@Override
	public void pCaseItemChange() {
		this.pmsDataAccess.getDiagnosisContainer().refresh();
		
		// TODO Auto-generated method stub

	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// lblTitle
		lblTitle = new Label();
		lblTitle.setImmediate(false);
		lblTitle.setWidth("-1px");
		lblTitle.setHeight("-1px");
		lblTitle.setValue("Details Diagnosen");
		mainLayout.addComponent(lblTitle, "top:20.0px;left:20.0px;");

		// btnToggleDiagnosisView
		btnToggleDiagnosisView = new Button();
		btnToggleDiagnosisView.setCaption("Tabellenansicht");
		btnToggleDiagnosisView.setImmediate(true);
		btnToggleDiagnosisView.setWidth("120px");
		btnToggleDiagnosisView.setHeight("-1px");
		mainLayout.addComponent(btnToggleDiagnosisView,
				"top:20.0px;left:240.0px;");

		// btnNewDiagnosis
		btnNewDiagnosis = new Button();
		btnNewDiagnosis.setCaption("Neue Diagnose");
		btnNewDiagnosis.setImmediate(true);
		btnNewDiagnosis.setWidth("120px");
		btnNewDiagnosis.setHeight("-1px");
		mainLayout.addComponent(btnNewDiagnosis, "top:20.0px;left:380.0px;");

		// panel_3
		panel_3 = buildPanel_3();
		mainLayout.addComponent(panel_3,
				"top:80.0px;right:24.0px;bottom:90.0px;left:20.0px;");

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_3() {
		// common part: create layout
		panel_3 = new Panel();
		panel_3.setImmediate(false);
		panel_3.setWidth("100.0%");
		panel_3.setHeight("100.0%");

		// verticalLayout_3
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("-1px");
		verticalLayout_3.setHeight("-1px");
		verticalLayout_3.setMargin(false);
		panel_3.setContent(verticalLayout_3);

		return panel_3;
	}

}
