package ch.bfh.ti.soed.white.mhc_pms.ui;

import ch.bfh.ti.soed.white.mhc_pms.controller.NavigationEvent;
import ch.bfh.ti.soed.white.mhc_pms.controller.NewItemListener;
import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentController;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Label;

public class EditDiagnosisComponent extends PmsComponentController implements NewItemListener {

	private class SaveDiagnosisButtonListener implements Button.ClickListener {
		private static final long serialVersionUID = 7137875461203747513L;

		@Override
		public void buttonClick(ClickEvent event) {
			// TODO Auto-generated method stub
			
			EditDiagnosisComponent.this.fireUIActivationEvent(true);
			EditDiagnosisComponent.this
					.fireComponentChangeEvent(NavigationEvent.DIAGNOSIS_BACK);
			EditDiagnosisComponent.this.setNewItem(false);
		}
		
	}
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnCancel;
	@AutoGenerated
	private Button btnSave;
	@AutoGenerated
	private Label lblTitle;
	private static final long serialVersionUID = 1756507024961174367L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public EditDiagnosisComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.btnSave.addClickListener(new SaveDiagnosisButtonListener());
		this.addBtnCancelListener();
	}

	private void addBtnCancelListener() {
		// TODO Auto-generated method stub
		
		this.btnCancel.addClickListener(new Button.ClickListener() {
			
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				
				EditDiagnosisComponent.this.fireUIActivationEvent(true);
				EditDiagnosisComponent.this
						.fireComponentChangeEvent(NavigationEvent.DIAGNOSIS_BACK);
				EditDiagnosisComponent.this.setNewItem(false);
			}
		});
		
	}

	@Override
	public void setNewItem(boolean value) {
		// TODO Auto-generated method stub
		
	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// lblTitle
		lblTitle = new Label();
		lblTitle.setImmediate(false);
		lblTitle.setWidth("-1px");
		lblTitle.setHeight("-1px");
		lblTitle.setValue("Neue Diagnose");
		mainLayout.addComponent(lblTitle, "top:20.0px;left:20.0px;");
		
		// btnSave
		btnSave = new Button();
		btnSave.setCaption("Speichern");
		btnSave.setImmediate(false);
		btnSave.setWidth("100px");
		btnSave.setHeight("-1px");
		mainLayout.addComponent(btnSave, "top:20.0px;left:200.0px;");
		
		// btnCancel
		btnCancel = new Button();
		btnCancel.setCaption("Abbrechen");
		btnCancel.setImmediate(false);
		btnCancel.setWidth("100px");
		btnCancel.setHeight("-1px");
		mainLayout.addComponent(btnCancel, "top:20.0px;left:320.0px;");
		
		return mainLayout;
	}

}
