package ch.bfh.ti.soed.white.mhc_pms.ui;

import java.text.DateFormat;
import java.util.Date;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Window;

public class HomeTitleBarComponent extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnSearch;
	@AutoGenerated
	private Button btnFilter;
	@AutoGenerated
	private Button btnLogout;
	@AutoGenerated
	private Label lblDate;
	@AutoGenerated
	private Label lblTitle;
	private static final long serialVersionUID = 1789220932106607837L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public HomeTitleBarComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.lblTitle.setContentMode(ContentMode.HTML);
		this.lblTitle.setValue("<h1><b>MHC PMS</b></h1>");
		// TODO string eliminieren
		this.lblDate.setContentMode(ContentMode.HTML);
		this.lblDate.setValue("<h1><b>" + DateFormat.getDateInstance(DateFormat.LONG).format(new Date()) + "</b></h1>");
		
		// TODO implement Popup
		//PopupView popupView = new PopupView("Test", new PatientTableComponent());
//		PopupView popupView = new PopupView("Test", new InlineDateField());
//		mainLayout.addComponent(popupView, "top:40.0px;left:600.0px;");
		
		this.btnFilter.addClickListener(new Button.ClickListener() {
			
			private static final long serialVersionUID = -4555286792720366254L;

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				HomeTitleBarComponent.this.getUI().addWindow(new Window("Filter"));
			}
		});
		
		this.btnSearch.addClickListener(new Button.ClickListener() {
			
			private static final long serialVersionUID = -4194378010453446670L;

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				HomeTitleBarComponent.this.getUI().addWindow(new Window("Suchen"));
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// lblTitle
		lblTitle = new Label();
		lblTitle.setImmediate(false);
		lblTitle.setWidth("160px");
		lblTitle.setHeight("60px");
		lblTitle.setValue("Label");
		mainLayout.addComponent(lblTitle, "top:20.0px;left:60.0px;");
		
		// lblDate
		lblDate = new Label();
		lblDate.setImmediate(false);
		lblDate.setWidth("280px");
		lblDate.setHeight("60px");
		lblDate.setValue("Label");
		mainLayout.addComponent(lblDate, "top:20.0px;left:260.0px;");
		
		// btnLogout
		btnLogout = new Button();
		btnLogout.setCaption("Logout");
		btnLogout.setImmediate(true);
		btnLogout.setWidth("80px");
		btnLogout.setHeight("-1px");
		mainLayout.addComponent(btnLogout, "top:100.0px;left:60.0px;");
		
		// btnFilter
		btnFilter = new Button();
		btnFilter.setCaption("Filtern");
		btnFilter.setImmediate(true);
		btnFilter.setWidth("80px");
		btnFilter.setHeight("-1px");
		mainLayout.addComponent(btnFilter, "top:100.0px;left:180.0px;");
		
		// btnSearch
		btnSearch = new Button();
		btnSearch.setCaption("Suchen");
		btnSearch.setImmediate(true);
		btnSearch.setWidth("80px");
		btnSearch.setHeight("-1px");
		mainLayout.addComponent(btnSearch, "top:100.0px;left:300.0px;");
		
		return mainLayout;
	}

}
