package ch.bfh.ti.soed.white.mhc_pms.ui;

import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentController;
import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentListener;
import ch.bfh.ti.soed.white.mhc_pms.data.PCase;
import ch.bfh.ti.soed.white.mhc_pms.data.PmsDataAccessCreator;
import ch.bfh.ti.soed.white.mhc_pms.data.UnknownUserException;
import ch.bfh.ti.soed.white.mhc_pms.data.enums.CaseStatus;
import ch.bfh.ti.soed.white.mhc_pms.security.PmsPermission.Operation;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.themes.Reindeer;

/**
 * UI Class for medication
 * 
 * @author Group White, I2p, BFH Berne, <a href="https://github.com/fabaff/ch.bfh.bti7081.s2013.white">Contact</a>
 * @version 1.0.0
 */
class MedicationComponent extends PmsComponentController implements
		PmsComponentListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label lblView;
	@AutoGenerated
	private Button btnEditMedication;
	@AutoGenerated
	private Button btnDeleteMedication;
	@AutoGenerated
	private Button btnNewMedication;
	private static final long serialVersionUID = -4426948260684454466L;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public MedicationComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// Static UI elements
		this.lblView.addStyleName(Reindeer.LABEL_H2);
		this.lblView.setValue("Medikamente");
	}

	private void setPermissions() throws UnknownUserException {
		Object pCaseItemId = PmsDataAccessCreator.getDataAccess()
				.getPCaseContainer().getCurrentItemId();
		PCase currentPCase = PmsDataAccessCreator.getDataAccess()
				.getPCaseContainer().getCurrentItem();
		Object itemId = PmsDataAccessCreator.getDataAccess().getMedicationContainer().getCurrentItemId();
		
		boolean isOpen = (currentPCase == null || currentPCase.getCaseStatus() != CaseStatus.CLOSED);

		this.btnNewMedication.setEnabled(PmsDataAccessCreator.getDataAccess()
				.getPermission().hasPermission(Operation.NEW_MEDICATION)
				&& pCaseItemId != null && isOpen);
		this.btnEditMedication.setEnabled(PmsDataAccessCreator.getDataAccess()
				.getPermission().hasPermission(Operation.EDIT_MEDICATION)
				&& itemId != null && isOpen);
		this.btnDeleteMedication.setEnabled(PmsDataAccessCreator
				.getDataAccess().getPermission()
				.hasPermission(Operation.DELETE_MEDICATION)
				&& itemId != null && isOpen);
	}

	@Override
	public void enter(ViewChangeEvent event) {
	}

	@Override
	public void pCaseItemChange() {
		try {
			this.setPermissions();
		} catch (UnknownUserException e) {
			Notification.show(e.getInvalidUserMessage(),
					Notification.Type.HUMANIZED_MESSAGE);
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// btnNewMedication
		btnNewMedication = new Button();
		btnNewMedication.setCaption("Neues Medikament");
		btnNewMedication.setImmediate(true);
		btnNewMedication.setWidth("140px");
		btnNewMedication.setHeight("-1px");
		mainLayout.addComponent(btnNewMedication, "top:20.0px;left:250.0px;");

		// btnDeleteMedication
		btnDeleteMedication = new Button();
		btnDeleteMedication.setCaption("Medikament löschen");
		btnDeleteMedication.setImmediate(true);
		btnDeleteMedication.setWidth("-1px");
		btnDeleteMedication.setHeight("-1px");
		mainLayout
				.addComponent(btnDeleteMedication, "top:20.0px;left:580.0px;");

		// btnEditMedication
		btnEditMedication = new Button();
		btnEditMedication.setCaption("Medikament bearbeiten");
		btnEditMedication.setImmediate(true);
		btnEditMedication.setWidth("160px");
		btnEditMedication.setHeight("-1px");
		mainLayout.addComponent(btnEditMedication, "top:20.0px;left:400.0px;");

		// lblView
		lblView = new Label();
		lblView.setImmediate(false);
		lblView.setWidth("-1px");
		lblView.setHeight("-1px");
		lblView.setValue("Label");
		mainLayout.addComponent(lblView, "top:20.0px;left:20.0px;");

		return mainLayout;
	}

}
