package ch.bfh.ti.soed.white.mhc_pms.ui;

import java.text.DateFormat;
import java.util.Date;

import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentController;
import ch.bfh.ti.soed.white.mhc_pms.controller.UIActivationListener;
import ch.bfh.ti.soed.white.mhc_pms.data.ContainerCollection;
import ch.bfh.ti.soed.white.mhc_pms.data.PmsDataAccess;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.Navigator;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Label;

/**
 * @author Gruppe White, I2p, BFH Bern, <a
 *         href="https://github.com/fabaff/ch.bfh.bti7081.s2013.white"
 *         >Contact</a>
 * @version 0.0.2
 * @since 0.0.1
 * 
 * 
 */
class MenuBarComponent extends PmsComponentController implements
		UIActivationListener {
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label lblDate;
	@AutoGenerated
	private Label lblTitle;
	@AutoGenerated
	private Button btnForward;
	@AutoGenerated
	private Button btnBack;
	@AutoGenerated
	private Button btnMedication;
	@AutoGenerated
	private Button btnDiagnosis;
	@AutoGenerated
	private Button btnPatientProgress;
	@AutoGenerated
	private Button btnCaseInfo;
	@AutoGenerated
	private Button btnPatientInfo;
	@AutoGenerated
	private Button btnHome;

	enum ButtonEnum {
		HOME, PATIENT_INFO, CASE_INFO, PATIENT_PROGRESS, DIAGNOSIS, MEDICATION
	}

	private static final long serialVersionUID = 2747224025250099607L;

	private ContainerCollection pmsContainers;
	
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 * 
	 * @param mhcPmsMainUI
	 */
	public MenuBarComponent(final Navigator navigator) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.pmsContainers = PmsDataAccess.getContainers();
		this.pmsContainers.getPCaseContainer().refresh();
		
		// TODO Add theme support
		// https://vaadin.com/book/-/page/themes.html
		// https://vaadin.com/wiki/-/wiki/Main/Vaadin+Theme+Tips+and+Tricks
		this.lblTitle.setContentMode(ContentMode.HTML);
		this.lblTitle.setValue("<h2><b>MHC PMS</b></h2>");
		this.lblDate.setContentMode(ContentMode.HTML);
		this.lblDate.setValue("<h2><b>"
				+ DateFormat.getDateInstance(DateFormat.LONG)
						.format(new Date()) + "</b></h2>");

		this.addHomeButtonClickListener(navigator);
		this.addPatientInfoButtonClickListener(navigator);
		this.addCaseInfoButtonClickListener(navigator);
		this.addPatientProgressButtonClickListener(navigator);
		this.addDiagnosisButtonClickListener(navigator);
		this.addMedicationButtonClickListener(navigator);
		this.addBackButtonClickListener();
		this.addForwardButtonClickListener();
	}

	private void addForwardButtonClickListener() {
		this.btnForward.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -8920612956190749837L;

			@Override
			public void buttonClick(ClickEvent event) {
				Object id = MenuBarComponent.this.pmsContainers.getPCaseContainer().incrementCurrentPCaseItemId();
				if (id != null) {
					MenuBarComponent.this.firePCaseItemChangeEvent(id);
				}
			}
		});
	}

	private void addBackButtonClickListener() {
		this.btnBack.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -5118039408005091733L;

			@Override
			public void buttonClick(ClickEvent event) {
				Object id = MenuBarComponent.this.pmsContainers.getPCaseContainer().decrementCurrentPCaseItemId();
				if (id != null) {
					MenuBarComponent.this.firePCaseItemChangeEvent(id);
				}
			}
		});
	}

	private void addMedicationButtonClickListener(final Navigator navigator) {
		this.btnMedication.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -5118039408005091733L;

			@Override
			public void buttonClick(ClickEvent event) {
				navigator.navigateTo(ButtonEnum.MEDICATION.toString());
			}
		});
	}

	private void addDiagnosisButtonClickListener(final Navigator navigator) {
		this.btnDiagnosis.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -5118039408005091733L;

			@Override
			public void buttonClick(ClickEvent event) {
				navigator.navigateTo(ButtonEnum.DIAGNOSIS.toString());
			}
		});
	}

	private void addPatientProgressButtonClickListener(final Navigator navigator) {
		this.btnPatientProgress.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -5118039408005091733L;

			@Override
			public void buttonClick(ClickEvent event) {
				navigator.navigateTo(ButtonEnum.PATIENT_PROGRESS.toString());
			}
		});		
	}

	private void addCaseInfoButtonClickListener(final Navigator navigator) {
		this.btnCaseInfo.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -5118039408005091733L;

			@Override
			public void buttonClick(ClickEvent event) {
				navigator.navigateTo(ButtonEnum.CASE_INFO.toString());
			}
		});
	}

	private void addPatientInfoButtonClickListener(final Navigator navigator) {
		this.btnPatientInfo.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -5118039408005091733L;

			@Override
			public void buttonClick(ClickEvent event) {
				navigator.navigateTo(ButtonEnum.PATIENT_INFO.toString());
			}
		});
	}

	private void addHomeButtonClickListener(final Navigator navigator) {
		this.btnHome.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -5118039408005091733L;

			@Override
			public void buttonClick(ClickEvent event) {
				navigator.navigateTo(ButtonEnum.HOME.toString());
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// btnHome
		btnHome = new Button();
		btnHome.setCaption("Übersicht");
		btnHome.setImmediate(true);
		btnHome.setWidth("100px");
		btnHome.setHeight("-1px");
		mainLayout.addComponent(btnHome, "top:180.0px;left:20.0px;");

		// btnPatientInfo
		btnPatientInfo = new Button();
		btnPatientInfo.setCaption("Patient");
		btnPatientInfo.setImmediate(true);
		btnPatientInfo.setWidth("100px");
		btnPatientInfo.setHeight("-1px");
		mainLayout.addComponent(btnPatientInfo, "top:220.0px;left:20.0px;");

		// btnCaseInfo
		btnCaseInfo = new Button();
		btnCaseInfo.setCaption("Fallinfo");
		btnCaseInfo.setImmediate(true);
		btnCaseInfo.setWidth("100px");
		btnCaseInfo.setHeight("-1px");
		mainLayout.addComponent(btnCaseInfo, "top:260.0px;left:20.0px;");

		// btnPatientProgress
		btnPatientProgress = new Button();
		btnPatientProgress.setCaption("Verlauf");
		btnPatientProgress.setImmediate(true);
		btnPatientProgress.setWidth("100px");
		btnPatientProgress.setHeight("-1px");
		mainLayout.addComponent(btnPatientProgress, "top:300.0px;left:20.0px;");

		// btnDiagnosis
		btnDiagnosis = new Button();
		btnDiagnosis.setCaption("Diagnosen");
		btnDiagnosis.setImmediate(true);
		btnDiagnosis.setWidth("100px");
		btnDiagnosis.setHeight("-1px");
		mainLayout.addComponent(btnDiagnosis, "top:340.0px;left:20.0px;");

		// btnMedication
		btnMedication = new Button();
		btnMedication.setCaption("Medikamente");
		btnMedication.setImmediate(true);
		btnMedication.setWidth("100px");
		btnMedication.setHeight("-1px");
		mainLayout.addComponent(btnMedication, "top:380.0px;left:20.0px;");

		// btnBack
		btnBack = new Button();
		btnBack.setCaption("Zurück");
		btnBack.setImmediate(true);
		btnBack.setWidth("-1px");
		btnBack.setHeight("-1px");
		mainLayout.addComponent(btnBack, "top:460.0px;left:13.0px;");

		// btnForward
		btnForward = new Button();
		btnForward.setCaption("Vor");
		btnForward.setImmediate(true);
		btnForward.setWidth("67px");
		btnForward.setHeight("-1px");
		mainLayout.addComponent(btnForward, "top:460.0px;left:93.0px;");

		// lblTitle
		lblTitle = new Label();
		lblTitle.setImmediate(false);
		lblTitle.setWidth("140px");
		lblTitle.setHeight("40px");
		lblTitle.setValue("Label");
		mainLayout.addComponent(lblTitle, "top:20.0px;left:20.0px;");

		// lblDate
		lblDate = new Label();
		lblDate.setImmediate(false);
		lblDate.setWidth("140px");
		lblDate.setHeight("40px");
		lblDate.setValue("Label");
		mainLayout.addComponent(lblDate, "top:80.0px;left:20.0px;");

		return mainLayout;
	}

	@Override
	public void enableUIComponents(boolean value) {
		this.btnHome.setEnabled(value);
		this.btnPatientInfo.setEnabled(value);
		this.btnCaseInfo.setEnabled(value);
		this.btnPatientProgress.setEnabled(value);
		this.btnDiagnosis.setEnabled(value);
		this.btnMedication.setEnabled(value);
		this.btnBack.setEnabled(value);
		this.btnForward.setEnabled(value);
	}

}
