package ch.bfh.ti.soed.white.mhc_pms.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;

public class NewPatientComponent extends PmsComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TextField txtFamilyDoctorPostalCode;
	@AutoGenerated
	private TextField txtFamilyDoctorFax;
	@AutoGenerated
	private TextField txtFamilyDoctorLocation;
	@AutoGenerated
	private TextField txtFamilyDoctorFirstName;
	@AutoGenerated
	private TextField txtFamilyDoctorLastName;
	@AutoGenerated
	private TextField txtFamilyDoctorAddress;
	@AutoGenerated
	private TextField txtNextOfKinFirstName;
	@AutoGenerated
	private TextField txtNextOfKinLastName;
	@AutoGenerated
	private TextField txtNextOfKinAddress;
	@AutoGenerated
	private TextField txtNextOfKinPhone;
	@AutoGenerated
	private TextField txtNextOfKinHomeLocation;
	@AutoGenerated
	private TextField txtNextOfKinPostalCode;
	@AutoGenerated
	private TextField ttPostalCode;
	@AutoGenerated
	private TextField txtHomeLocation;
	@AutoGenerated
	private TextField txtCountry;
	@AutoGenerated
	private TextField txtMobilePhone;
	@AutoGenerated
	private TextField txtPhoneBusiness;
	@AutoGenerated
	private TextField txtEmail;
	@AutoGenerated
	private TextField txtNextOfKin;
	@AutoGenerated
	private TextField txtPhonePrivate;
	@AutoGenerated
	private TextField txtAddress;
	@AutoGenerated
	private TextField txtReligion;
	@AutoGenerated
	private TextField txtCommuncationLanguage;
	@AutoGenerated
	private TextField txtNationality;
	@AutoGenerated
	private TextField txtCivilStatus;
	@AutoGenerated
	private TextField txtFirstName;
	@AutoGenerated
	private ComboBox cmbGender;
	@AutoGenerated
	private PopupDateField dateFieldDateOfBirth;
	@AutoGenerated
	private TextField txtLastName;
	@AutoGenerated
	private TextField txtMotherLanguage;
	@AutoGenerated
	private Button btnCancel;
	@AutoGenerated
	private Button btnAddPatient;
	private static final long serialVersionUID = 611645331656829049L;


	//private BeanItem<Patient> newPatientItem;

	private FieldGroup fieldGroup;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public NewPatientComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		
		// TODO saubere Implementierung
//		this.newPatientItem = new BeanItem<Patient>(new Patient());
//		fieldGroup = new FieldGroup(this.newPatientItem);
//		fieldGroup.bind(this.txtFirstName, "firstName");
//		fieldGroup.bind(this.txtLastName, "lastName");
//		fieldGroup.bind(this.txtCivilStatus, "civilStatus");
//		fieldGroup.bind(this.txtMotherLanguage, "motherLanguage");
//		fieldGroup.bind(this.txtNationality, "nationality");
//		fieldGroup.bind(this.cmbGender, "gender");
//		fieldGroup.bind(this.cmbKindOfTreatment, "kindOfTreatment");
//		fieldGroup.bind(this.dateFieldDateOfBirth, "dateOfBirth");
		

		this.btnAddPatient.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
//				// TODO Cast vermeiden
//				MhcPmsContainer<? extends MhcPmsItem> cont = PmsDataAccess.getInstance().getCurrentContainer(Patient.class);
//				if (cont != null) {
//					MhcPmsContainer<Patient> container = (MhcPmsContainer<Patient>) cont;
//					
//					newPatient.setFirstName(txtFirstName.getValue());
//					newPatient.setLastName(txtLastName.getValue());
//					newPatient.setCivilStatus(txtCivilStatus.getValue());
//					newPatient.setDateOfBirth(dateFieldDateOfBirth.getValue());
//					newPatient.setGender(cmbGender.getValue().toString());
//					newPatient.setKindOfTreatment(cmbKindOfTreatment.getValue().toString());
//					newPatient.setMotherLanguage(txtMotherLanguage.getValue());
//					newPatient.setNationality(txtNationality.getValue());
//					container.addEntity(newPatient);
//					container.commit();
//					
//					NewPatientComponent.this.mainComponent
//							.updateComponentDataSource();
//					newPatient = new Patient();
//				}
//				NewPatientComponent.this.restoreUI();
//				NewPatientComponent.this.mainComponent
//						.updateComponentDataSource();
			}
		});

		this.btnCancel.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				NewPatientComponent.this.restoreUI();
			}
		});

		// TODO Combobox Values aus Container
		this.cmbGender.addItem("Weiblich");
		this.cmbGender.addItem("Männlich");
		this.cmbGender.setValue("Weiblich");
//		this.cmbKindOfTreatment.addItem("Ambulant");
//		this.cmbKindOfTreatment.addItem("Teilstationär");
//		this.cmbKindOfTreatment.addItem("Stationär");
//		this.cmbKindOfTreatment.setValue("Stationär");

	}

	private void restoreUI() {
//		Component title = this.mainComponent.getTitleBarComponent();
//		Component detail = this.mainComponent.getPatientInfoComponent();
//		this.mainComponent.setActiveComponents(title, detail);
//		this.mainComponent.enableMenuBar(true);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// btnAddPatient
		btnAddPatient = new Button();
		btnAddPatient.setCaption("Patient hinzufügen");
		btnAddPatient.setImmediate(true);
		btnAddPatient.setWidth("140px");
		btnAddPatient.setHeight("-1px");
		mainLayout.addComponent(btnAddPatient, "top:580.0px;left:20.0px;");
		
		// btnCancel
		btnCancel = new Button();
		btnCancel.setCaption("Abbrechen");
		btnCancel.setImmediate(true);
		btnCancel.setWidth("-1px");
		btnCancel.setHeight("-1px");
		mainLayout.addComponent(btnCancel, "top:580.0px;left:200.0px;");
		
		// txtMotherLanguage
		txtMotherLanguage = new TextField();
		txtMotherLanguage.setCaption("Muttersprache: ");
		txtMotherLanguage.setImmediate(false);
		txtMotherLanguage.setWidth("160px");
		txtMotherLanguage.setHeight("-1px");
		mainLayout.addComponent(txtMotherLanguage, "top:100.0px;left:20.0px;");
		
		// txtLastName
		txtLastName = new TextField();
		txtLastName.setCaption("Nachname: ");
		txtLastName.setImmediate(false);
		txtLastName.setWidth("160px");
		txtLastName.setHeight("-1px");
		mainLayout.addComponent(txtLastName, "top:40.0px;left:220.0px;");
		
		// dateFieldDateOfBirth
		dateFieldDateOfBirth = new PopupDateField();
		dateFieldDateOfBirth.setCaption("Geburtsdatum: ");
		dateFieldDateOfBirth.setImmediate(false);
		dateFieldDateOfBirth.setWidth("160px");
		dateFieldDateOfBirth.setHeight("-1px");
		mainLayout.addComponent(dateFieldDateOfBirth,
				"top:40.0px;left:620.0px;");
		
		// cmbGender
		cmbGender = new ComboBox();
		cmbGender.setCaption("Geschlecht: ");
		cmbGender.setImmediate(false);
		cmbGender.setWidth("160px");
		cmbGender.setHeight("-1px");
		mainLayout.addComponent(cmbGender, "top:40.0px;left:420.0px;");
		
		// txtFirstName
		txtFirstName = new TextField();
		txtFirstName.setCaption("Vorname: ");
		txtFirstName.setImmediate(false);
		txtFirstName.setWidth("160px");
		txtFirstName.setHeight("-1px");
		mainLayout.addComponent(txtFirstName, "top:40.0px;left:20.0px;");
		
		// txtCivilStatus
		txtCivilStatus = new TextField();
		txtCivilStatus.setCaption("Zivilstand: ");
		txtCivilStatus.setImmediate(false);
		txtCivilStatus.setWidth("160px");
		txtCivilStatus.setHeight("-1px");
		mainLayout.addComponent(txtCivilStatus, "top:100.0px;left:420.0px;");
		
		// txtNationality
		txtNationality = new TextField();
		txtNationality.setCaption("Nationalität: ");
		txtNationality.setImmediate(false);
		txtNationality.setWidth("160px");
		txtNationality.setHeight("-1px");
		mainLayout.addComponent(txtNationality, "top:100.0px;left:620.0px;");
		
		// txtCommuncationLanguage
		txtCommuncationLanguage = new TextField();
		txtCommuncationLanguage.setCaption("Verständigung: ");
		txtCommuncationLanguage.setImmediate(false);
		txtCommuncationLanguage.setWidth("160px");
		txtCommuncationLanguage.setHeight("-1px");
		mainLayout.addComponent(txtCommuncationLanguage,
				"top:100.0px;left:220.0px;");
		
		// txtReligion
		txtReligion = new TextField();
		txtReligion.setCaption("Religion: ");
		txtReligion.setImmediate(false);
		txtReligion.setWidth("160px");
		txtReligion.setHeight("-1px");
		mainLayout.addComponent(txtReligion, "top:160.0px;left:20.0px;");
		
		// txtAddress
		txtAddress = new TextField();
		txtAddress.setCaption("Adresse: ");
		txtAddress.setImmediate(false);
		txtAddress.setWidth("160px");
		txtAddress.setHeight("-1px");
		mainLayout.addComponent(txtAddress, "top:160.0px;left:220.0px;");
		
		// txtPhonePrivate
		txtPhonePrivate = new TextField();
		txtPhonePrivate.setCaption("Telefon Privat: ");
		txtPhonePrivate.setImmediate(false);
		txtPhonePrivate.setWidth("160px");
		txtPhonePrivate.setHeight("-1px");
		mainLayout.addComponent(txtPhonePrivate, "top:220.0px;left:220.0px;");
		
		// txtNextOfKin
		txtNextOfKin = new TextField();
		txtNextOfKin.setCaption("Angehöriger: ");
		txtNextOfKin.setImmediate(false);
		txtNextOfKin.setWidth("160px");
		txtNextOfKin.setHeight("-1px");
		mainLayout.addComponent(txtNextOfKin, "top:340.0px;left:20.0px;");
		
		// txtEmail
		txtEmail = new TextField();
		txtEmail.setCaption("E-Mail: ");
		txtEmail.setImmediate(false);
		txtEmail.setWidth("160px");
		txtEmail.setHeight("-1px");
		mainLayout.addComponent(txtEmail, "top:280.0px;left:20.0px;");
		
		// txtPhoneBusiness
		txtPhoneBusiness = new TextField();
		txtPhoneBusiness.setCaption("Telefon Geschäft: ");
		txtPhoneBusiness.setImmediate(false);
		txtPhoneBusiness.setWidth("160px");
		txtPhoneBusiness.setHeight("-1px");
		mainLayout.addComponent(txtPhoneBusiness, "top:220.0px;left:420.0px;");
		
		// txtMobilePhone
		txtMobilePhone = new TextField();
		txtMobilePhone.setCaption("Handy: ");
		txtMobilePhone.setImmediate(false);
		txtMobilePhone.setWidth("160px");
		txtMobilePhone.setHeight("-1px");
		mainLayout.addComponent(txtMobilePhone, "top:220.0px;left:620.0px;");
		
		// txtCountry
		txtCountry = new TextField();
		txtCountry.setCaption("Land: ");
		txtCountry.setImmediate(false);
		txtCountry.setWidth("160px");
		txtCountry.setHeight("-1px");
		mainLayout.addComponent(txtCountry, "top:220.0px;left:20.0px;");
		
		// txtHomeLocation
		txtHomeLocation = new TextField();
		txtHomeLocation.setCaption("Ort: ");
		txtHomeLocation.setImmediate(false);
		txtHomeLocation.setWidth("160px");
		txtHomeLocation.setHeight("-1px");
		mainLayout.addComponent(txtHomeLocation, "top:160.0px;left:620.0px;");
		
		// ttPostalCode
		ttPostalCode = new TextField();
		ttPostalCode.setCaption("Postleitzahl: ");
		ttPostalCode.setImmediate(false);
		ttPostalCode.setWidth("160px");
		ttPostalCode.setHeight("-1px");
		mainLayout.addComponent(ttPostalCode, "top:160.0px;left:420.0px;");
		
		// txtNextOfKinPostalCode
		txtNextOfKinPostalCode = new TextField();
		txtNextOfKinPostalCode.setCaption("Postleitzahl: ");
		txtNextOfKinPostalCode.setImmediate(false);
		txtNextOfKinPostalCode.setWidth("160px");
		txtNextOfKinPostalCode.setHeight("-1px");
		mainLayout.addComponent(txtNextOfKinPostalCode,
				"top:400.0px;left:20.0px;");
		
		// txtNextOfKinHomeLocation
		txtNextOfKinHomeLocation = new TextField();
		txtNextOfKinHomeLocation.setCaption("Ort: ");
		txtNextOfKinHomeLocation.setImmediate(false);
		txtNextOfKinHomeLocation.setWidth("160px");
		txtNextOfKinHomeLocation.setHeight("-1px");
		mainLayout.addComponent(txtNextOfKinHomeLocation,
				"top:400.0px;left:220.0px;");
		
		// txtNextOfKinPhone
		txtNextOfKinPhone = new TextField();
		txtNextOfKinPhone.setCaption("Telefon: ");
		txtNextOfKinPhone.setImmediate(false);
		txtNextOfKinPhone.setWidth("160px");
		txtNextOfKinPhone.setHeight("-1px");
		mainLayout.addComponent(txtNextOfKinPhone, "top:400.0px;left:420.0px;");
		
		// txtNextOfKinAddress
		txtNextOfKinAddress = new TextField();
		txtNextOfKinAddress.setCaption("Adresse: ");
		txtNextOfKinAddress.setImmediate(false);
		txtNextOfKinAddress.setWidth("160px");
		txtNextOfKinAddress.setHeight("-1px");
		mainLayout.addComponent(txtNextOfKinAddress,
				"top:340.0px;left:620.0px;");
		
		// txtNextOfKinLastName
		txtNextOfKinLastName = new TextField();
		txtNextOfKinLastName.setCaption("Nachname: ");
		txtNextOfKinLastName.setImmediate(false);
		txtNextOfKinLastName.setWidth("160px");
		txtNextOfKinLastName.setHeight("-1px");
		mainLayout.addComponent(txtNextOfKinLastName,
				"top:340.0px;left:420.0px;");
		
		// txtNextOfKinFirstName
		txtNextOfKinFirstName = new TextField();
		txtNextOfKinFirstName.setCaption("Vorname: ");
		txtNextOfKinFirstName.setImmediate(false);
		txtNextOfKinFirstName.setWidth("160px");
		txtNextOfKinFirstName.setHeight("-1px");
		mainLayout.addComponent(txtNextOfKinFirstName,
				"top:340.0px;left:220.0px;");
		
		// txtFamilyDoctorAddress
		txtFamilyDoctorAddress = new TextField();
		txtFamilyDoctorAddress.setCaption("Adresse Hausarzt: ");
		txtFamilyDoctorAddress.setImmediate(false);
		txtFamilyDoctorAddress.setWidth("160px");
		txtFamilyDoctorAddress.setHeight("-1px");
		mainLayout.addComponent(txtFamilyDoctorAddress,
				"top:460.0px;left:420.0px;");
		
		// txtFamilyDoctorLastName
		txtFamilyDoctorLastName = new TextField();
		txtFamilyDoctorLastName.setCaption("Nachname Hausarzt: ");
		txtFamilyDoctorLastName.setImmediate(false);
		txtFamilyDoctorLastName.setWidth("160px");
		txtFamilyDoctorLastName.setHeight("-1px");
		mainLayout.addComponent(txtFamilyDoctorLastName,
				"top:460.0px;left:220.0px;");
		
		// txtFamilyDoctorFirstName
		txtFamilyDoctorFirstName = new TextField();
		txtFamilyDoctorFirstName.setCaption("Vorname Hausarzt:");
		txtFamilyDoctorFirstName.setImmediate(false);
		txtFamilyDoctorFirstName.setWidth("160px");
		txtFamilyDoctorFirstName.setHeight("-1px");
		mainLayout.addComponent(txtFamilyDoctorFirstName,
				"top:460.0px;left:20.0px;");
		
		// txtFamilyDoctorLocation
		txtFamilyDoctorLocation = new TextField();
		txtFamilyDoctorLocation.setCaption("Ort Hausarzt: ");
		txtFamilyDoctorLocation.setImmediate(false);
		txtFamilyDoctorLocation.setWidth("160px");
		txtFamilyDoctorLocation.setHeight("-1px");
		mainLayout.addComponent(txtFamilyDoctorLocation,
				"top:520.0px;left:20.0px;");
		
		// txtFamilyDoctorFax
		txtFamilyDoctorFax = new TextField();
		txtFamilyDoctorFax.setCaption("Fax Hausarzt: ");
		txtFamilyDoctorFax.setImmediate(false);
		txtFamilyDoctorFax.setWidth("160px");
		txtFamilyDoctorFax.setHeight("-1px");
		mainLayout
				.addComponent(txtFamilyDoctorFax, "top:520.0px;left:220.0px;");
		
		// txtFamilyDoctorPostalCode
		txtFamilyDoctorPostalCode = new TextField();
		txtFamilyDoctorPostalCode.setCaption("Postleitzahl Hausarzt: ");
		txtFamilyDoctorPostalCode.setImmediate(false);
		txtFamilyDoctorPostalCode.setWidth("160px");
		txtFamilyDoctorPostalCode.setHeight("-1px");
		mainLayout.addComponent(txtFamilyDoctorPostalCode,
				"top:460.0px;left:620.0px;");
		
		return mainLayout;
	}

}
