package ch.bfh.ti.soed.white.mhc_pms.ui;

import ch.bfh.ti.soed.white.mhc_pms.data.PmsDataAccess;
import ch.bfh.ti.soed.white.mhc_pms.security.Nurse;

import com.vaadin.addon.jpacontainer.EntityItem;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;

class PatientInfoComponent extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label lblNationality;
	@AutoGenerated
	private Label lblCivilStatus;
	@AutoGenerated
	private Label lblMotherLanguage;
	@AutoGenerated
	private Button btnNewPatient;
	private static final long serialVersionUID = -6090834279643277087L;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PatientInfoComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

//		this.patientFieldGroup = new FieldGroup();
//		this.patientFieldGroup.bind(this.lblFirstName, "");
		
//		Nurse permission = UserSingleton.getUser().getUIPermission();
//		this.btnNewPatient.setEnabled(permission.isNewPatientAllowed());
		
		this.btnNewPatient.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
//				Component title =  PatientInfoComponent.this.mainComponent.getTitleBarComponent();
//				Component detail = PatientInfoComponent.this.mainComponent.getNewPatientComponent();
//				PatientInfoComponent.this.mainComponent.setActiveComponents(title, detail);
//				PatientInfoComponent.this.mainComponent.enableMenuBar(false);
			}
		});
		
		this.updateComponentDataSource();
	}

	protected void updateComponentDataSource() {
//		EntityItem<? extends MhcPmsItem> itemP = PmsDataAccess.getInstance().getCurrentContainer(Patient.class).getCurrentItem();
//		if (itemP != null && itemP.getEntity() instanceof Patient) {
//			Patient pat = (Patient) itemP.getEntity();
//			this.lblCivilStatus.setValue(pat.getCivilStatus());
//			this.lblMotherLanguage.setValue(pat.getMotherLanguage());
//			this.lblNationality.setValue(pat.getNationality());
//		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// btnNewPatient
		btnNewPatient = new Button();
		btnNewPatient.setCaption("Neuer Patient");
		btnNewPatient.setImmediate(true);
		btnNewPatient.setWidth("-1px");
		btnNewPatient.setHeight("-1px");
		mainLayout.addComponent(btnNewPatient, "top:20.0px;left:20.0px;");
		
		// lblMotherLanguage
		lblMotherLanguage = new Label();
		lblMotherLanguage.setCaption("Muttersprache");
		lblMotherLanguage.setImmediate(false);
		lblMotherLanguage.setWidth("-1px");
		lblMotherLanguage.setHeight("-1px");
		mainLayout.addComponent(lblMotherLanguage, "top:78.0px;left:20.0px;");
		
		// lblCivilStatus
		lblCivilStatus = new Label();
		lblCivilStatus.setCaption("Zivilstand");
		lblCivilStatus.setImmediate(false);
		lblCivilStatus.setWidth("-1px");
		lblCivilStatus.setHeight("-1px");
		mainLayout.addComponent(lblCivilStatus, "top:78.0px;left:169.0px;");
		
		// lblNationality
		lblNationality = new Label();
		lblNationality.setCaption("Nationalität");
		lblNationality.setImmediate(false);
		lblNationality.setWidth("-1px");
		lblNationality.setHeight("-1px");
		mainLayout.addComponent(lblNationality, "top:78.0px;left:280.0px;");
		
		return mainLayout;
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}

}
