package ch.bfh.ti.soed.white.mhc_pms.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;

class PatientInfoComponent extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label lblFamilyDoctorFax;
	@AutoGenerated
	private Label lblFamilyDoctorLocation;
	@AutoGenerated
	private Label lblFamilyDoctorAddress;
	@AutoGenerated
	private Label lblFamilyDoctorPostalCode;
	@AutoGenerated
	private Label lblFamilyDoctorLastName;
	@AutoGenerated
	private Label lblFamilyDoctorFirstName;
	@AutoGenerated
	private Label lblNextOfKinPhone;
	@AutoGenerated
	private Label lblNextOfKinHomeLocation;
	@AutoGenerated
	private Label lblNextOfKinAddress;
	@AutoGenerated
	private Label lblNextOfKinPostalCode;
	@AutoGenerated
	private Label lblNextOfKinLastName;
	@AutoGenerated
	private Label lblNextOfKinFirstName;
	@AutoGenerated
	private Label lblNextOfKin;
	@AutoGenerated
	private Label lblEmail;
	@AutoGenerated
	private Label lblMobilePhone;
	@AutoGenerated
	private Label lblPhoneBusiness;
	@AutoGenerated
	private Label lblPhonePrivate;
	@AutoGenerated
	private Label lblCountry;
	@AutoGenerated
	private Label lblHomeLocation;
	@AutoGenerated
	private Label lblPostalCode;
	@AutoGenerated
	private Label lblAddress;
	@AutoGenerated
	private Label lblReligion;
	@AutoGenerated
	private Label lblCommuncationLanguage;
	@AutoGenerated
	private Label lblNationality;
	@AutoGenerated
	private Label lblCivilStatus;
	@AutoGenerated
	private Label lblMotherLanguage;
	@AutoGenerated
	private Button btnNewPatient;
	private static final long serialVersionUID = -6090834279643277087L;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PatientInfoComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

//		this.patientFieldGroup = new FieldGroup();
//		this.patientFieldGroup.bind(this.lblFirstName, "");
		
//		NursePermission permission = UserSingleton.getUser().getUIPermission();
//		this.btnNewPatient.setEnabled(permission.isNewPatientAllowed());
		
		this.btnNewPatient.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
//				Component title =  PatientInfoComponent.this.mainComponent.getTitleBarComponent();
//				Component detail = PatientInfoComponent.this.mainComponent.getNewPatientComponent();
//				PatientInfoComponent.this.mainComponent.setActiveComponents(title, detail);
//				PatientInfoComponent.this.mainComponent.enableMenuBar(false);
			}
		});
		
		this.updateComponentDataSource();
	}

	protected void updateComponentDataSource() {
//		EntityItem<? extends MhcPmsItem> itemP = PmsDataAccess.getInstance().getCurrentContainer(Patient.class).getCurrentItem();
//		if (itemP != null && itemP.getEntity() instanceof Patient) {
//			Patient pat = (Patient) itemP.getEntity();
//			this.lblCivilStatus.setValue(pat.getCivilStatus());
//			this.lblMotherLanguage.setValue(pat.getMotherLanguage());
//			this.lblNationality.setValue(pat.getNationality());
//		}
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// btnNewPatient
		btnNewPatient = new Button();
		btnNewPatient.setCaption("Neuer Patient");
		btnNewPatient.setImmediate(true);
		btnNewPatient.setWidth("-1px");
		btnNewPatient.setHeight("-1px");
		mainLayout.addComponent(btnNewPatient, "top:20.0px;left:20.0px;");
		
		// lblMotherLanguage
		lblMotherLanguage = new Label();
		lblMotherLanguage.setCaption("Muttersprache: ");
		lblMotherLanguage.setImmediate(false);
		lblMotherLanguage.setWidth("-1px");
		lblMotherLanguage.setHeight("-1px");
		lblMotherLanguage.setValue("Label");
		mainLayout.addComponent(lblMotherLanguage, "top:80.0px;left:20.0px;");
		
		// lblCivilStatus
		lblCivilStatus = new Label();
		lblCivilStatus.setCaption("Zivilstand: ");
		lblCivilStatus.setImmediate(false);
		lblCivilStatus.setWidth("-1px");
		lblCivilStatus.setHeight("-1px");
		lblCivilStatus.setValue("Label");
		mainLayout.addComponent(lblCivilStatus, "top:80.0px;left:340.0px;");
		
		// lblNationality
		lblNationality = new Label();
		lblNationality.setCaption("Nationalität: ");
		lblNationality.setImmediate(false);
		lblNationality.setWidth("-1px");
		lblNationality.setHeight("-1px");
		lblNationality.setValue("Label");
		mainLayout.addComponent(lblNationality, "top:80.0px;left:500.0px;");
		
		// lblCommuncationLanguage
		lblCommuncationLanguage = new Label();
		lblCommuncationLanguage.setCaption("Verständigung: ");
		lblCommuncationLanguage.setImmediate(false);
		lblCommuncationLanguage.setWidth("-1px");
		lblCommuncationLanguage.setHeight("18px");
		lblCommuncationLanguage.setValue("Label");
		mainLayout.addComponent(lblCommuncationLanguage,
				"top:80.0px;left:180.0px;");
		
		// lblReligion
		lblReligion = new Label();
		lblReligion.setCaption("Religion: ");
		lblReligion.setImmediate(false);
		lblReligion.setWidth("-1px");
		lblReligion.setHeight("-1px");
		lblReligion.setValue("Label");
		mainLayout.addComponent(lblReligion, "top:80.0px;left:660.0px;");
		
		// lblAddress
		lblAddress = new Label();
		lblAddress.setCaption("Adresse: ");
		lblAddress.setImmediate(false);
		lblAddress.setWidth("-1px");
		lblAddress.setHeight("-1px");
		lblAddress.setValue("Label");
		mainLayout.addComponent(lblAddress, "top:140.0px;left:20.0px;");
		
		// lblPostalCode
		lblPostalCode = new Label();
		lblPostalCode.setCaption("Postleitzahl: ");
		lblPostalCode.setImmediate(false);
		lblPostalCode.setWidth("-1px");
		lblPostalCode.setHeight("-1px");
		lblPostalCode.setValue("Label");
		mainLayout.addComponent(lblPostalCode, "top:140.0px;left:180.0px;");
		
		// lblHomeLocation
		lblHomeLocation = new Label();
		lblHomeLocation.setCaption("Ort: ");
		lblHomeLocation.setImmediate(false);
		lblHomeLocation.setWidth("-1px");
		lblHomeLocation.setHeight("-1px");
		lblHomeLocation.setValue("Label");
		mainLayout.addComponent(lblHomeLocation, "top:140.0px;left:340.0px;");
		
		// lblCountry
		lblCountry = new Label();
		lblCountry.setCaption("Land: ");
		lblCountry.setImmediate(false);
		lblCountry.setWidth("-1px");
		lblCountry.setHeight("-1px");
		lblCountry.setValue("Label");
		mainLayout.addComponent(lblCountry, "top:140.0px;left:500.0px;");
		
		// lblPhonePrivate
		lblPhonePrivate = new Label();
		lblPhonePrivate.setCaption("Telefon Privat: ");
		lblPhonePrivate.setImmediate(false);
		lblPhonePrivate.setWidth("-1px");
		lblPhonePrivate.setHeight("-1px");
		lblPhonePrivate.setValue("Label");
		mainLayout.addComponent(lblPhonePrivate, "top:140.0px;left:660.0px;");
		
		// lblPhoneBusiness
		lblPhoneBusiness = new Label();
		lblPhoneBusiness.setCaption("Telefon Geschäft: ");
		lblPhoneBusiness.setImmediate(false);
		lblPhoneBusiness.setWidth("-1px");
		lblPhoneBusiness.setHeight("-1px");
		lblPhoneBusiness.setValue("Label");
		mainLayout.addComponent(lblPhoneBusiness, "top:200.0px;left:20.0px;");
		
		// lblMobilePhone
		lblMobilePhone = new Label();
		lblMobilePhone.setCaption("Handy: ");
		lblMobilePhone.setImmediate(false);
		lblMobilePhone.setWidth("-1px");
		lblMobilePhone.setHeight("-1px");
		lblMobilePhone.setValue("Label");
		mainLayout.addComponent(lblMobilePhone, "top:200.0px;left:180.0px;");
		
		// lblEmail
		lblEmail = new Label();
		lblEmail.setCaption("E-Mail:");
		lblEmail.setImmediate(false);
		lblEmail.setWidth("-1px");
		lblEmail.setHeight("-1px");
		lblEmail.setValue("Label");
		mainLayout.addComponent(lblEmail, "top:200.0px;left:340.0px;");
		
		// lblNextOfKin
		lblNextOfKin = new Label();
		lblNextOfKin.setCaption("Angehöriger: ");
		lblNextOfKin.setImmediate(false);
		lblNextOfKin.setWidth("-1px");
		lblNextOfKin.setHeight("-1px");
		lblNextOfKin.setValue("Label");
		mainLayout.addComponent(lblNextOfKin, "top:260.0px;left:20.0px;");
		
		// lblNextOfKinFirstName
		lblNextOfKinFirstName = new Label();
		lblNextOfKinFirstName.setCaption("Vorname: ");
		lblNextOfKinFirstName.setImmediate(false);
		lblNextOfKinFirstName.setWidth("-1px");
		lblNextOfKinFirstName.setHeight("-1px");
		lblNextOfKinFirstName.setValue("Label");
		mainLayout.addComponent(lblNextOfKinFirstName,
				"top:260.0px;left:180.0px;");
		
		// lblNextOfKinLastName
		lblNextOfKinLastName = new Label();
		lblNextOfKinLastName.setCaption("Nachname:");
		lblNextOfKinLastName.setImmediate(false);
		lblNextOfKinLastName.setWidth("-1px");
		lblNextOfKinLastName.setHeight("-1px");
		lblNextOfKinLastName.setValue("Label");
		mainLayout.addComponent(lblNextOfKinLastName,
				"top:260.0px;left:340.0px;");
		
		// lblNextOfKinPostalCode
		lblNextOfKinPostalCode = new Label();
		lblNextOfKinPostalCode.setCaption("Postleitzahl: ");
		lblNextOfKinPostalCode.setImmediate(false);
		lblNextOfKinPostalCode.setWidth("-1px");
		lblNextOfKinPostalCode.setHeight("-1px");
		lblNextOfKinPostalCode.setValue("Label");
		mainLayout.addComponent(lblNextOfKinPostalCode,
				"top:260.0px;left:660.0px;");
		
		// lblNextOfKinAddress
		lblNextOfKinAddress = new Label();
		lblNextOfKinAddress.setCaption("Adresse: ");
		lblNextOfKinAddress.setImmediate(false);
		lblNextOfKinAddress.setWidth("-1px");
		lblNextOfKinAddress.setHeight("-1px");
		lblNextOfKinAddress.setValue("Label");
		mainLayout.addComponent(lblNextOfKinAddress,
				"top:260.0px;left:500.0px;");
		
		// lblNextOfKinHomeLocation
		lblNextOfKinHomeLocation = new Label();
		lblNextOfKinHomeLocation.setCaption("Ort: ");
		lblNextOfKinHomeLocation.setImmediate(false);
		lblNextOfKinHomeLocation.setWidth("-1px");
		lblNextOfKinHomeLocation.setHeight("-1px");
		lblNextOfKinHomeLocation.setValue("Label");
		mainLayout.addComponent(lblNextOfKinHomeLocation,
				"top:320.0px;left:20.0px;");
		
		// lblNextOfKinPhone
		lblNextOfKinPhone = new Label();
		lblNextOfKinPhone.setCaption("Telefon: ");
		lblNextOfKinPhone.setImmediate(false);
		lblNextOfKinPhone.setWidth("-1px");
		lblNextOfKinPhone.setHeight("-1px");
		lblNextOfKinPhone.setValue("Label");
		mainLayout.addComponent(lblNextOfKinPhone, "top:320.0px;left:180.0px;");
		
		// lblFamilyDoctorFirstName
		lblFamilyDoctorFirstName = new Label();
		lblFamilyDoctorFirstName.setCaption("Vorname Hausarzt:");
		lblFamilyDoctorFirstName.setImmediate(false);
		lblFamilyDoctorFirstName.setWidth("-1px");
		lblFamilyDoctorFirstName.setHeight("-1px");
		lblFamilyDoctorFirstName.setValue("Label");
		mainLayout.addComponent(lblFamilyDoctorFirstName,
				"top:380.0px;left:20.0px;");
		
		// lblFamilyDoctorLastName
		lblFamilyDoctorLastName = new Label();
		lblFamilyDoctorLastName.setCaption("Nachname Hausarzt: ");
		lblFamilyDoctorLastName.setImmediate(false);
		lblFamilyDoctorLastName.setWidth("-1px");
		lblFamilyDoctorLastName.setHeight("-1px");
		lblFamilyDoctorLastName.setValue("Label");
		mainLayout.addComponent(lblFamilyDoctorLastName,
				"top:380.0px;left:180.0px;");
		
		// lblFamilyDoctorPostalCode
		lblFamilyDoctorPostalCode = new Label();
		lblFamilyDoctorPostalCode.setCaption("Postleitzahl Hausarzt: ");
		lblFamilyDoctorPostalCode.setImmediate(false);
		lblFamilyDoctorPostalCode.setWidth("-1px");
		lblFamilyDoctorPostalCode.setHeight("-1px");
		lblFamilyDoctorPostalCode.setValue("Label");
		mainLayout.addComponent(lblFamilyDoctorPostalCode,
				"top:380.0px;left:500.0px;");
		
		// lblFamilyDoctorAddress
		lblFamilyDoctorAddress = new Label();
		lblFamilyDoctorAddress.setCaption("Adresse Hausarzt: ");
		lblFamilyDoctorAddress.setImmediate(false);
		lblFamilyDoctorAddress.setWidth("-1px");
		lblFamilyDoctorAddress.setHeight("-1px");
		lblFamilyDoctorAddress.setValue("Label");
		mainLayout.addComponent(lblFamilyDoctorAddress,
				"top:380.0px;left:340.0px;");
		
		// lblFamilyDoctorLocation
		lblFamilyDoctorLocation = new Label();
		lblFamilyDoctorLocation.setCaption("Ort Hausarzt: ");
		lblFamilyDoctorLocation.setImmediate(false);
		lblFamilyDoctorLocation.setWidth("-1px");
		lblFamilyDoctorLocation.setHeight("-1px");
		lblFamilyDoctorLocation.setValue("Label");
		mainLayout.addComponent(lblFamilyDoctorLocation,
				"top:380.0px;left:660.0px;");
		
		// lblFamilyDoctorFax
		lblFamilyDoctorFax = new Label();
		lblFamilyDoctorFax.setCaption("Fax Hausarzt: ");
		lblFamilyDoctorFax.setImmediate(false);
		lblFamilyDoctorFax.setWidth("-1px");
		lblFamilyDoctorFax.setHeight("-1px");
		lblFamilyDoctorFax.setValue("Label");
		mainLayout.addComponent(lblFamilyDoctorFax, "top:440.0px;left:20.0px;");
		
		return mainLayout;
	}

}
