package ch.bfh.ti.soed.white.mhc_pms.ui;

import ch.bfh.ti.soed.white.mhc_pms.controller.NavigationEvent;
import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentController;
import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentListener;
import ch.bfh.ti.soed.white.mhc_pms.data.ContainerCollection;
import ch.bfh.ti.soed.white.mhc_pms.data.PCase;
import ch.bfh.ti.soed.white.mhc_pms.data.PmsDataAccess;
import ch.bfh.ti.soed.white.mhc_pms.security.PmsPermission;
import ch.bfh.ti.soed.white.mhc_pms.security.PmsPermission.Element;
import ch.bfh.ti.soed.white.mhc_pms.util.ValueConverter;

import com.vaadin.addon.jpacontainer.EntityItem;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

/**
 * @author		Gruppe White, I2p, BFH Bern, <a href="https://github.com/fabaff/ch.bfh.bti7081.s2013.white">Contact</a>
 * @version		0.0.2 
 * @since		0.0.1
 * 
 * UI Class for patient information 
 */
class PatientInfoComponent extends PmsComponentController implements PmsComponentListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Panel panComm;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private Label lblMotherLanguage;
	@AutoGenerated
	private Label lblCommuncationLanguage;
	@AutoGenerated
	private Label lblPhonePrivate;
	@AutoGenerated
	private Label lblPhoneBusiness;
	@AutoGenerated
	private Label lblMobilePhone;
	@AutoGenerated
	private Label lblEmail;
	@AutoGenerated
	private Panel panGeneral;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Label lblAddress;
	@AutoGenerated
	private Label lblCivilStatus;
	@AutoGenerated
	private Label lblNationality;
	@AutoGenerated
	private Label lblReligion;
	@AutoGenerated
	private Label lblCountry;
	@AutoGenerated
	private Label lblHomeLocation;
	@AutoGenerated
	private Label lblPostalCode;
	@AutoGenerated
	private Panel panFamily;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Label lblNextOfKinPhone;
	@AutoGenerated
	private Label lblNextOfKinHomeLocation;
	@AutoGenerated
	private Label lblNextOfKinPostalCode;
	@AutoGenerated
	private Label lblNextOfKinAddress;
	@AutoGenerated
	private Label lblNextOfKinLastName;
	@AutoGenerated
	private Label lblNextOfKinFirstName;
	@AutoGenerated
	private Label lblNextOfKin;
	@AutoGenerated
	private Panel panFamDoc;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Label lblFamilyDoctorFax;
	@AutoGenerated
	private Label lblFamilyDoctorLocation;
	@AutoGenerated
	private Label lblFamilyDoctorPostalCode;
	@AutoGenerated
	private Label lblFamilyDoctorAddress;
	@AutoGenerated
	private Label lblFamilyDoctorLastName;
	@AutoGenerated
	private Label lblFamilyDoctorFirstName;
	@AutoGenerated
	private Button btnNewPatient;
	private static final long serialVersionUID = -6090834279643277087L;
	
	
	private ContainerCollection pmsContainers;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PatientInfoComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		this.pmsContainers = PmsDataAccess.getContainers();
		this.pmsContainers.getPCaseContainer().refresh();
		
		PmsPermission permission = new PmsPermission(this.pmsContainers.getCurrentUser().getUserGroup());
		this.btnNewPatient.setEnabled(permission.hasPermission(Element.NEW_PATIENT));
		
		this.addListeners();
		this.pCaseItemChange(this.pmsContainers.getPCaseContainer().getCurrentPCaseId());
		
	}

	private void addListeners() {
		this.btnNewPatient.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = 1L;
			@Override
			public void buttonClick(ClickEvent event) {
				PatientInfoComponent.this.fireUIActivationEvent(false);
				PatientInfoComponent.this.fireComponentChangeEvent(NavigationEvent.PATIENT);
			}
		});
	}

	@Override
	public void pCaseItemChange(Object itemId) {
		EntityItem<PCase> entityItem = this.pmsContainers.getPCaseContainer().getItem(itemId);
		PCase item = new PCase();
		
		if (entityItem != null) {
			item = entityItem.getEntity();
		} 
			this.setBasicPatientInfoValues(item);
			this.setNextOfKinValues(item);
			this.setFamilyDoctorValues(item);
	}

	private void setFamilyDoctorValues(PCase item) {
		this.lblFamilyDoctorFirstName.setValue(item.getFamilyDoctorFirstName());
		this.lblFamilyDoctorLastName.setValue(item.getFamilyDoctorLastName());
		this.lblFamilyDoctorAddress.setValue(item.getFamilyDoctorAddress());
		this.lblFamilyDoctorPostalCode.setValue(item.getFamilyDoctorPostalCode());
		this.lblFamilyDoctorLocation.setValue(item.getFamilyDoctorLocation());
		this.lblFamilyDoctorFax.setValue(item.getFamilyDoctorFax());
	}

	private void setNextOfKinValues(PCase item) {
		this.lblNextOfKin.setValue(item.getNextOfKin());
		this.lblNextOfKinFirstName.setValue(item.getNextOfKinFirstName());
		this.lblNextOfKinLastName.setValue(item.getNextOfKinLastName());
		this.lblNextOfKinAddress.setValue(item.getNextOfKinAddress());
		this.lblNextOfKinPostalCode.setValue(item.getNextOfKinPostalCode());
		this.lblNextOfKinHomeLocation.setValue(item.getNextOfKinHomeLocation());
		this.lblNextOfKinPhone.setValue(item.getNextOfKinPhone());
	}

	private void setBasicPatientInfoValues(PCase item) {
		this.lblMotherLanguage.setValue(item.getMotherLanguage());
		this.lblCivilStatus.setValue(ValueConverter.convertString(item.getCivilStatus()));
		this.lblNationality.setValue(item.getNationality());
		this.lblReligion.setValue(item.getReligion());
		this.lblAddress.setValue(item.getAddress());
		this.lblPostalCode.setValue(item.getPostalCode());
		this.lblHomeLocation.setValue(item.getHomeLocation());
		this.lblCountry.setValue(item.getCountry());
		this.lblPhonePrivate.setValue(item.getPhonePrivate());
		this.lblPhoneBusiness.setValue(item.getPhoneBusiness());
		this.lblMobilePhone.setValue(item.getPhoneMobile());
		this.lblEmail.setValue(item.geteMail());
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// btnNewPatient
		btnNewPatient = new Button();
		btnNewPatient.setCaption("Neuer Patient");
		btnNewPatient.setImmediate(true);
		btnNewPatient.setWidth("-1px");
		btnNewPatient.setHeight("-1px");
		mainLayout.addComponent(btnNewPatient, "top:20.0px;left:20.0px;");
		
		// panFamDoc
		panFamDoc = buildPanFamDoc();
		mainLayout.addComponent(panFamDoc, "top:60.0px;left:480.0px;");
		
		// panFamily
		panFamily = buildPanFamily();
		mainLayout.addComponent(panFamily, "top:60.0px;left:320.0px;");
		
		// panGeneral
		panGeneral = buildPanGeneral();
		mainLayout.addComponent(panGeneral, "top:60.0px;left:20.0px;");
		
		// panComm
		panComm = buildPanComm();
		mainLayout.addComponent(panComm, "top:60.0px;left:160.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanFamDoc() {
		// common part: create layout
		panFamDoc = new Panel();
		panFamDoc.setImmediate(false);
		panFamDoc.setWidth("-1px");
		panFamDoc.setHeight("-1px");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		panFamDoc.setContent(verticalLayout_1);
		
		return panFamDoc;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(true);
		
		// lblFamilyDoctorFirstName
		lblFamilyDoctorFirstName = new Label();
		lblFamilyDoctorFirstName.setCaption("Vorname Hausarzt:");
		lblFamilyDoctorFirstName.setImmediate(false);
		lblFamilyDoctorFirstName.setWidth("-1px");
		lblFamilyDoctorFirstName.setHeight("-1px");
		lblFamilyDoctorFirstName.setValue("Label");
		verticalLayout_1.addComponent(lblFamilyDoctorFirstName);
		
		// lblFamilyDoctorLastName
		lblFamilyDoctorLastName = new Label();
		lblFamilyDoctorLastName.setCaption("Nachname Hausarzt: ");
		lblFamilyDoctorLastName.setImmediate(false);
		lblFamilyDoctorLastName.setWidth("-1px");
		lblFamilyDoctorLastName.setHeight("-1px");
		lblFamilyDoctorLastName.setValue("Label");
		verticalLayout_1.addComponent(lblFamilyDoctorLastName);
		
		// lblFamilyDoctorAddress
		lblFamilyDoctorAddress = new Label();
		lblFamilyDoctorAddress.setCaption("Adresse Hausarzt: ");
		lblFamilyDoctorAddress.setImmediate(false);
		lblFamilyDoctorAddress.setWidth("-1px");
		lblFamilyDoctorAddress.setHeight("-1px");
		lblFamilyDoctorAddress.setValue("Label");
		verticalLayout_1.addComponent(lblFamilyDoctorAddress);
		
		// lblFamilyDoctorPostalCode
		lblFamilyDoctorPostalCode = new Label();
		lblFamilyDoctorPostalCode.setCaption("Postleitzahl Hausarzt: ");
		lblFamilyDoctorPostalCode.setImmediate(false);
		lblFamilyDoctorPostalCode.setWidth("-1px");
		lblFamilyDoctorPostalCode.setHeight("-1px");
		lblFamilyDoctorPostalCode.setValue("Label");
		verticalLayout_1.addComponent(lblFamilyDoctorPostalCode);
		
		// lblFamilyDoctorLocation
		lblFamilyDoctorLocation = new Label();
		lblFamilyDoctorLocation.setCaption("Ort Hausarzt: ");
		lblFamilyDoctorLocation.setImmediate(false);
		lblFamilyDoctorLocation.setWidth("-1px");
		lblFamilyDoctorLocation.setHeight("-1px");
		lblFamilyDoctorLocation.setValue("Label");
		verticalLayout_1.addComponent(lblFamilyDoctorLocation);
		
		// lblFamilyDoctorFax
		lblFamilyDoctorFax = new Label();
		lblFamilyDoctorFax.setCaption("Fax Hausarzt: ");
		lblFamilyDoctorFax.setImmediate(false);
		lblFamilyDoctorFax.setWidth("-1px");
		lblFamilyDoctorFax.setHeight("-1px");
		lblFamilyDoctorFax.setValue("Label");
		verticalLayout_1.addComponent(lblFamilyDoctorFax);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private Panel buildPanFamily() {
		// common part: create layout
		panFamily = new Panel();
		panFamily.setImmediate(false);
		panFamily.setWidth("-1px");
		panFamily.setHeight("-1px");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panFamily.setContent(verticalLayout_2);
		
		return panFamily;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("132.38%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(true);
		
		// lblNextOfKin
		lblNextOfKin = new Label();
		lblNextOfKin.setCaption("Angehöriger: ");
		lblNextOfKin.setImmediate(false);
		lblNextOfKin.setWidth("-1px");
		lblNextOfKin.setHeight("-1px");
		lblNextOfKin.setValue("Label");
		verticalLayout_2.addComponent(lblNextOfKin);
		
		// lblNextOfKinFirstName
		lblNextOfKinFirstName = new Label();
		lblNextOfKinFirstName.setCaption("Vorname: ");
		lblNextOfKinFirstName.setImmediate(false);
		lblNextOfKinFirstName.setWidth("-1px");
		lblNextOfKinFirstName.setHeight("-1px");
		lblNextOfKinFirstName.setValue("Label");
		verticalLayout_2.addComponent(lblNextOfKinFirstName);
		
		// lblNextOfKinLastName
		lblNextOfKinLastName = new Label();
		lblNextOfKinLastName.setCaption("Nachname:");
		lblNextOfKinLastName.setImmediate(false);
		lblNextOfKinLastName.setWidth("-1px");
		lblNextOfKinLastName.setHeight("-1px");
		lblNextOfKinLastName.setValue("Label");
		verticalLayout_2.addComponent(lblNextOfKinLastName);
		
		// lblNextOfKinAddress
		lblNextOfKinAddress = new Label();
		lblNextOfKinAddress.setCaption("Adresse: ");
		lblNextOfKinAddress.setImmediate(false);
		lblNextOfKinAddress.setWidth("-1px");
		lblNextOfKinAddress.setHeight("-1px");
		lblNextOfKinAddress.setValue("Label");
		verticalLayout_2.addComponent(lblNextOfKinAddress);
		
		// lblNextOfKinPostalCode
		lblNextOfKinPostalCode = new Label();
		lblNextOfKinPostalCode.setCaption("Postleitzahl: ");
		lblNextOfKinPostalCode.setImmediate(false);
		lblNextOfKinPostalCode.setWidth("-1px");
		lblNextOfKinPostalCode.setHeight("-1px");
		lblNextOfKinPostalCode.setValue("Label");
		verticalLayout_2.addComponent(lblNextOfKinPostalCode);
		
		// lblNextOfKinHomeLocation
		lblNextOfKinHomeLocation = new Label();
		lblNextOfKinHomeLocation.setCaption("Ort: ");
		lblNextOfKinHomeLocation.setImmediate(false);
		lblNextOfKinHomeLocation.setWidth("-1px");
		lblNextOfKinHomeLocation.setHeight("-1px");
		lblNextOfKinHomeLocation.setValue("Label");
		verticalLayout_2.addComponent(lblNextOfKinHomeLocation);
		
		// lblNextOfKinPhone
		lblNextOfKinPhone = new Label();
		lblNextOfKinPhone.setCaption("Telefon: ");
		lblNextOfKinPhone.setImmediate(false);
		lblNextOfKinPhone.setWidth("-1px");
		lblNextOfKinPhone.setHeight("-1px");
		lblNextOfKinPhone.setValue("Label");
		verticalLayout_2.addComponent(lblNextOfKinPhone);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private Panel buildPanGeneral() {
		// common part: create layout
		panGeneral = new Panel();
		panGeneral.setImmediate(false);
		panGeneral.setWidth("-1px");
		panGeneral.setHeight("-1px");
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		panGeneral.setContent(verticalLayout_3);
		
		return panGeneral;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("117.82%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(true);
		
		// lblPostalCode
		lblPostalCode = new Label();
		lblPostalCode.setCaption("Postleitzahl: ");
		lblPostalCode.setImmediate(false);
		lblPostalCode.setWidth("-1px");
		lblPostalCode.setHeight("-1px");
		lblPostalCode.setValue("Label");
		verticalLayout_3.addComponent(lblPostalCode);
		
		// lblHomeLocation
		lblHomeLocation = new Label();
		lblHomeLocation.setCaption("Ort: ");
		lblHomeLocation.setImmediate(false);
		lblHomeLocation.setWidth("-1px");
		lblHomeLocation.setHeight("-1px");
		lblHomeLocation.setValue("Label");
		verticalLayout_3.addComponent(lblHomeLocation);
		
		// lblCountry
		lblCountry = new Label();
		lblCountry.setCaption("Land: ");
		lblCountry.setImmediate(false);
		lblCountry.setWidth("-1px");
		lblCountry.setHeight("-1px");
		lblCountry.setValue("Label");
		verticalLayout_3.addComponent(lblCountry);
		
		// lblReligion
		lblReligion = new Label();
		lblReligion.setCaption("Religion: ");
		lblReligion.setImmediate(false);
		lblReligion.setWidth("-1px");
		lblReligion.setHeight("-1px");
		lblReligion.setValue("Label");
		verticalLayout_3.addComponent(lblReligion);
		
		// lblNationality
		lblNationality = new Label();
		lblNationality.setCaption("Nationalität: ");
		lblNationality.setImmediate(false);
		lblNationality.setWidth("-1px");
		lblNationality.setHeight("-1px");
		lblNationality.setValue("Label");
		verticalLayout_3.addComponent(lblNationality);
		
		// lblCivilStatus
		lblCivilStatus = new Label();
		lblCivilStatus.setCaption("Zivilstand: ");
		lblCivilStatus.setImmediate(false);
		lblCivilStatus.setWidth("-1px");
		lblCivilStatus.setHeight("-1px");
		lblCivilStatus.setValue("Label");
		verticalLayout_3.addComponent(lblCivilStatus);
		
		// lblAddress
		lblAddress = new Label();
		lblAddress.setCaption("Adresse: ");
		lblAddress.setImmediate(false);
		lblAddress.setWidth("-1px");
		lblAddress.setHeight("-1px");
		lblAddress.setValue("Label");
		verticalLayout_3.addComponent(lblAddress);
		
		return verticalLayout_3;
	}

	@AutoGenerated
	private Panel buildPanComm() {
		// common part: create layout
		panComm = new Panel();
		panComm.setImmediate(false);
		panComm.setWidth("140px");
		panComm.setHeight("-1px");
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		panComm.setContent(verticalLayout_4);
		
		return panComm;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("-1px");
		verticalLayout_4.setHeight("100.0%");
		verticalLayout_4.setMargin(true);
		
		// lblEmail
		lblEmail = new Label();
		lblEmail.setCaption("E-Mail:");
		lblEmail.setImmediate(false);
		lblEmail.setWidth("-1px");
		lblEmail.setHeight("-1px");
		lblEmail.setValue("Label");
		verticalLayout_4.addComponent(lblEmail);
		
		// lblMobilePhone
		lblMobilePhone = new Label();
		lblMobilePhone.setCaption("Handy: ");
		lblMobilePhone.setImmediate(false);
		lblMobilePhone.setWidth("-1px");
		lblMobilePhone.setHeight("-1px");
		lblMobilePhone.setValue("Label");
		verticalLayout_4.addComponent(lblMobilePhone);
		
		// lblPhoneBusiness
		lblPhoneBusiness = new Label();
		lblPhoneBusiness.setCaption("Telefon Geschäft: ");
		lblPhoneBusiness.setImmediate(false);
		lblPhoneBusiness.setWidth("-1px");
		lblPhoneBusiness.setHeight("-1px");
		lblPhoneBusiness.setValue("Label");
		verticalLayout_4.addComponent(lblPhoneBusiness);
		
		// lblPhonePrivate
		lblPhonePrivate = new Label();
		lblPhonePrivate.setCaption("Telefon Privat: ");
		lblPhonePrivate.setImmediate(false);
		lblPhonePrivate.setWidth("-1px");
		lblPhonePrivate.setHeight("-1px");
		lblPhonePrivate.setValue("Label");
		verticalLayout_4.addComponent(lblPhonePrivate);
		
		// lblCommuncationLanguage
		lblCommuncationLanguage = new Label();
		lblCommuncationLanguage.setCaption("Verständigung: ");
		lblCommuncationLanguage.setImmediate(false);
		lblCommuncationLanguage.setWidth("-1px");
		lblCommuncationLanguage.setHeight("18px");
		lblCommuncationLanguage.setValue("Label");
		verticalLayout_4.addComponent(lblCommuncationLanguage);
		
		// lblMotherLanguage
		lblMotherLanguage = new Label();
		lblMotherLanguage.setCaption("Muttersprache: ");
		lblMotherLanguage.setImmediate(false);
		lblMotherLanguage.setWidth("-1px");
		lblMotherLanguage.setHeight("-1px");
		lblMotherLanguage.setValue("Label");
		verticalLayout_4.addComponent(lblMotherLanguage);
		
		return verticalLayout_4;
	}

}
