package ch.bfh.ti.soed.white.mhc_pms.ui;

import java.text.DateFormat;

import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponent;
import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentListener;
import ch.bfh.ti.soed.white.mhc_pms.data.PCase;
import ch.bfh.ti.soed.white.mhc_pms.data.PmsDataAccess;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Window;

class TitleBarComponent extends PmsComponent implements PmsComponentListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnLogout;
	@AutoGenerated
	private Button btnFilter;
	@AutoGenerated
	private Button btnSearch;
	@AutoGenerated
	private Label lblKindOfTreatment;
	@AutoGenerated
	private Label lblStatus;
	@AutoGenerated
	private Label lblGender;
	@AutoGenerated
	private Label lblDateOfBirth;
	@AutoGenerated
	private Label lblLastName;
	@AutoGenerated
	private Label lblPatientTitle;
	@AutoGenerated
	private Label lblFirstName;
	private static final long serialVersionUID = 1148948780923578333L;

	private PmsDataAccess dataAccess;
	
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public TitleBarComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.dataAccess = PmsDataAccess.getInstance();	
		
		// TODO Theme verwenden
		this.lblPatientTitle.setContentMode(ContentMode.HTML);
		this.lblPatientTitle.setValue("<h3><b>Patient: </b></h3>");
//		this.lblFirstName.setContentMode(ContentMode.HTML);
//		this.lblFirstName.setCaption("<b>Vorname: </b>");
//		this.lblLastName.setContentMode(ContentMode.HTML);
//		this.lblLastName.setCaption("<b>Nachname: </b>");
//		this.lblDateOfBirth.setContentMode(ContentMode.HTML);
//		this.lblDateOfBirth.setCaption("<b>Geburtsdatum: </b>");
//		this.lblGender.setContentMode(ContentMode.HTML);
//		this.lblGender.setCaption("<b>Geschlecht: </b>");
//		this.lblStatus.setContentMode(ContentMode.HTML);
//		this.lblStatus.setCaption("<b>Status: </b>");
//		this.lblKindOfTreatment.setContentMode(ContentMode.HTML);
//		this.lblKindOfTreatment.setCaption("<b>Behandlungsart: </b>");
		
		this.addButtonListeners();
		
		if (this.dataAccess.getPCaseContainer().size() != 0) {
			this.pCaseItemChange(this.dataAccess.getPCaseContainer().firstItemId());
		}
	}

	private void addButtonListeners() {
		this.btnFilter.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -4555286792720366254L;
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Implement filter
				TitleBarComponent.this.getUI().addWindow(
						new Window("Filter"));
			}
		});

		this.btnSearch.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -4194378010453446670L;
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Implement search
				TitleBarComponent.this.getUI().addWindow(
						new Window("Suchen"));
			}
		});
		
		this.btnLogout.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -7445511110217678724L;
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Implement Logout
				TitleBarComponent.this.getUI().addWindow(new Window("Logout"));
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// lblFirstName
		lblFirstName = new Label();
		lblFirstName.setCaption("Vorname:");
		lblFirstName.setImmediate(false);
		lblFirstName.setWidth("-1px");
		lblFirstName.setHeight("-1px");
		lblFirstName.setValue("XYZ");
		mainLayout.addComponent(lblFirstName, "top:42.0px;left:120.0px;");
		
		// lblPatientTitle
		lblPatientTitle = new Label();
		lblPatientTitle.setImmediate(false);
		lblPatientTitle.setWidth("-1px");
		lblPatientTitle.setHeight("-1px");
		lblPatientTitle.setValue("Patient: ");
		mainLayout.addComponent(lblPatientTitle, "top:20.0px;left:20.0px;");
		
		// lblLastName
		lblLastName = new Label();
		lblLastName.setCaption("Nachname:");
		lblLastName.setImmediate(false);
		lblLastName.setWidth("-1px");
		lblLastName.setHeight("-1px");
		lblLastName.setValue("XYZ");
		mainLayout.addComponent(lblLastName, "top:100.0px;left:120.0px;");
		
		// lblDateOfBirth
		lblDateOfBirth = new Label();
		lblDateOfBirth.setCaption("Geburtsdatum:");
		lblDateOfBirth.setImmediate(false);
		lblDateOfBirth.setWidth("-1px");
		lblDateOfBirth.setHeight("18px");
		lblDateOfBirth.setValue("XYZ");
		mainLayout.addComponent(lblDateOfBirth, "top:40.0px;left:340.0px;");
		
		// lblGender
		lblGender = new Label();
		lblGender.setCaption("Geschlecht:");
		lblGender.setImmediate(false);
		lblGender.setWidth("-1px");
		lblGender.setHeight("-1px");
		lblGender.setValue("XYZ");
		mainLayout.addComponent(lblGender, "top:100.0px;left:340.0px;");
		
		// lblStatus
		lblStatus = new Label();
		lblStatus.setCaption("Status:");
		lblStatus.setImmediate(false);
		lblStatus.setWidth("-1px");
		lblStatus.setHeight("-1px");
		lblStatus.setValue("XYZ");
		mainLayout.addComponent(lblStatus, "top:40.0px;left:500.0px;");
		
		// lblKindOfTreatment
		lblKindOfTreatment = new Label();
		lblKindOfTreatment.setCaption("Behandlungsart:");
		lblKindOfTreatment.setImmediate(false);
		lblKindOfTreatment.setWidth("-1px");
		lblKindOfTreatment.setHeight("-1px");
		lblKindOfTreatment.setValue("XYZ");
		mainLayout
				.addComponent(lblKindOfTreatment, "top:100.0px;left:500.0px;");
		
		// btnSearch
		btnSearch = new Button();
		btnSearch.setCaption("Suchen");
		btnSearch.setImmediate(true);
		btnSearch.setWidth("80px");
		btnSearch.setHeight("-1px");
		mainLayout.addComponent(btnSearch, "top:20.0px;left:680.0px;");
		
		// btnFilter
		btnFilter = new Button();
		btnFilter.setCaption("Filtern");
		btnFilter.setImmediate(true);
		btnFilter.setWidth("80px");
		btnFilter.setHeight("-1px");
		mainLayout.addComponent(btnFilter, "top:60.0px;left:680.0px;");
		
		// btnLogout
		btnLogout = new Button();
		btnLogout.setCaption("Logout");
		btnLogout.setImmediate(true);
		btnLogout.setWidth("80px");
		btnLogout.setHeight("-1px");
		mainLayout.addComponent(btnLogout, "top:100.0px;left:680.0px;");
		
		return mainLayout;
	}

	@Override
	public void pCaseItemChange(Object itemId) {
		 PCase item = this.dataAccess.getPCaseContainer().getItem(itemId).getEntity();
		 this.lblFirstName.setValue(item.getFirstName());
		 this.lblLastName.setValue(item.getLastName());
		 this.lblDateOfBirth.setValue(DateFormat.getDateInstance(DateFormat.SHORT).format(item.getDateOfBirth()));
		 this.lblGender.setValue(item.getGender().toString());
		 this.lblStatus.setValue(item.getStatus().toString());
		 this.lblKindOfTreatment.setValue(item.getKindOfTreatment().toString());
	}

}
