package ch.bfh.ti.soed.white.mhc_pms.ui;

import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentController;
import ch.bfh.ti.soed.white.mhc_pms.controller.PmsComponentListener;
import ch.bfh.ti.soed.white.mhc_pms.controller.UIActivationListener;
import ch.bfh.ti.soed.white.mhc_pms.data.ContainerCollection;
import ch.bfh.ti.soed.white.mhc_pms.data.PCase;
import ch.bfh.ti.soed.white.mhc_pms.data.PmsDataAccess;
import ch.bfh.ti.soed.white.mhc_pms.util.ValueConverter;

import com.vaadin.addon.jpacontainer.EntityItem;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Window;

/**
 * @author		Gruppe White, I2p, BFH Bern, <a href="https://github.com/fabaff/ch.bfh.bti7081.s2013.white">Contact</a>
 * @version		0.0.2 
 * @since		0.0.1
 * 
 * UI Class for layout header
 */
class TitleBarComponent extends PmsComponentController implements PmsComponentListener,
		UIActivationListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnLogout;
	@AutoGenerated
	private Button btnFilter;
	@AutoGenerated
	private Button btnSearch;
	@AutoGenerated
	private Label lblKindOfTreatment;
	@AutoGenerated
	private Label lblStatus;
	@AutoGenerated
	private Label lblGender;
	@AutoGenerated
	private Label lblDateOfBirth;
	@AutoGenerated
	private Label lblLastName;
	@AutoGenerated
	private Label lblFirstName;
	private static final long serialVersionUID = 1148948780923578333L;

	private ContainerCollection pmsContainers;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public TitleBarComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		this.pmsContainers = PmsDataAccess.getContainers();

		// TODO Use theme

		this.addFilterButtonClickListeners();
		this.addSearchButtonClickListeners();
		this.addLogoutButtonClickListeners();
		this.pCaseItemChange(this.pmsContainers.getPCaseContainer().getCurrentPCaseId());
	}

	private void addLogoutButtonClickListeners() {
		this.btnLogout.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -7445511110217678724L;

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Implement Logout
				TitleBarComponent.this.getUI().addWindow(new Window("Logout"));
			}
		});
	}

	private void addSearchButtonClickListeners() {
		this.btnSearch.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -4194378010453446670L;

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Implement search
				// PopupView popupView = new PopupView("Test", new
				// PatientTableComponent());
				// PopupView popupView = new PopupView("Test", new
				// InlineDateField());
				// mainLayout.addComponent(popupView,
				// "top:40.0px;left:600.0px;");
				TitleBarComponent.this.getUI().addWindow(new Window("Suchen"));
			}
		});
	}

	private void addFilterButtonClickListeners() {
		this.btnFilter.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -4555286792720366254L;

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Implement filter
				TitleBarComponent.this.getUI().addWindow(new Window("Filter"));
			}
		});
	}

	@Override
	public void pCaseItemChange(Object itemId) {
		EntityItem<PCase> entityItem = this.pmsContainers.getPCaseContainer().getItem(itemId);
		PCase item = new PCase();
		
		if (entityItem != null) {
			item = entityItem.getEntity();
		}
		
		// TODO Ugly layout hacks
		this.lblFirstName.setContentMode(ContentMode.HTML);
		this.lblFirstName.setValue("<h2><b>"+ item.getFirstName() + "</b></h2>");
		this.lblLastName.setContentMode(ContentMode.HTML);
		this.lblLastName.setValue("<h2><b>"+ item.getLastName() + "</b></h2>");
		//this.lblFirstName.setValue(item.getFirstName());
		//this.lblLastName.setValue(item.getLastName());
		this.lblDateOfBirth.setValue(ValueConverter.convertDate(item.getDateOfBirth()));
		this.lblGender.setValue(ValueConverter.convertString(item.getGender()));
		this.lblStatus.setValue(ValueConverter.convertString(item.getCaseStatus()));
		this.lblKindOfTreatment.setValue(ValueConverter.convertString(item.getKindOfTreatment()));
	}

	@Override
	public void enableUIComponents(boolean value) {
		this.btnFilter.setEnabled(value);
		this.btnLogout.setEnabled(value);
		this.btnSearch.setEnabled(value);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// lblFirstName
		lblFirstName = new Label();
		lblFirstName.setImmediate(false);
		lblFirstName.setWidth("-1px");
		lblFirstName.setHeight("-1px");
		lblFirstName.setValue("firstname");
		mainLayout.addComponent(lblFirstName, "top:0.0px;left:20.0px;");
		
		// lblLastName
		lblLastName = new Label();
		lblLastName.setImmediate(false);
		lblLastName.setWidth("-1px");
		lblLastName.setHeight("-1px");
		lblLastName.setValue("lastname");
		mainLayout.addComponent(lblLastName, "top:0.0px;left:160.0px;");
		
		// lblDateOfBirth
		lblDateOfBirth = new Label();
		lblDateOfBirth.setCaption("Geburtsdatum:");
		lblDateOfBirth.setImmediate(false);
		lblDateOfBirth.setWidth("23px");
		lblDateOfBirth.setHeight("100.0%");
		lblDateOfBirth.setValue("XYZ");
		mainLayout.addComponent(lblDateOfBirth,
				"top:60.0px;bottom:333.0px;left:20.0px;");
		
		// lblGender
		lblGender = new Label();
		lblGender.setCaption("Geschlecht:");
		lblGender.setImmediate(false);
		lblGender.setWidth("-1px");
		lblGender.setHeight("-1px");
		lblGender.setValue("XYZ");
		mainLayout.addComponent(lblGender, "top:60.0px;left:160.0px;");
		
		// lblStatus
		lblStatus = new Label();
		lblStatus.setCaption("Status:");
		lblStatus.setImmediate(false);
		lblStatus.setWidth("-1px");
		lblStatus.setHeight("18px");
		lblStatus.setValue("XYZ");
		mainLayout.addComponent(lblStatus, "bottom:487.0px;left:480.0px;");
		
		// lblKindOfTreatment
		lblKindOfTreatment = new Label();
		lblKindOfTreatment.setCaption("Behandlungsart:");
		lblKindOfTreatment.setImmediate(false);
		lblKindOfTreatment.setWidth("-1px");
		lblKindOfTreatment.setHeight("-1px");
		lblKindOfTreatment.setValue("XYZ");
		mainLayout.addComponent(lblKindOfTreatment, "top:60.0px;left:260.0px;");
		
		// btnSearch
		btnSearch = new Button();
		btnSearch.setCaption("Suchen");
		btnSearch.setImmediate(true);
		btnSearch.setWidth("-1px");
		btnSearch.setHeight("-1px");
		mainLayout.addComponent(btnSearch, "top:20.0px;right:180.0px;");
		
		// btnFilter
		btnFilter = new Button();
		btnFilter.setCaption("Filtern");
		btnFilter.setImmediate(true);
		btnFilter.setWidth("-1px");
		btnFilter.setHeight("-1px");
		mainLayout.addComponent(btnFilter, "top:20.0px;right:100.0px;");
		
		// btnLogout
		btnLogout = new Button();
		btnLogout.setCaption("Logout");
		btnLogout.setImmediate(true);
		btnLogout.setWidth("-1px");
		btnLogout.setHeight("-1px");
		mainLayout.addComponent(btnLogout, "top:20.0px;right:20.0px;");
		
		return mainLayout;
	}

}
